# SPDX-License-Identifier: Apache-2.0
#
# knowledge-mcp: a persistent memory and reasoning graph for LLMs, packaged as
# an MCP server.
#
# Three stages produce a FROM-scratch image carrying three binaries side by
# side under /app: the knowledge client (built here, statically linked against
# musl so it runs on a base with no libc), the knowledge-server, and the front
# binary that is the container's entrypoint.
#
# Two modes, both served by the same image:
#
#   docker run -p 127.0.0.1:15023:15023 -v knowledge:/data <image>
#   docker run -i --rm -v knowledge:/data <image> --stdio
#
# The build context is the repository ROOT. Both consumers see that layout —
# people building from this repository, and the release pipeline building from
# a staging tree — so the client is built from `.` rather than a subdirectory.

# ---- client stage -------------------------------------------------------------
# golang:1.26.5-alpine pins the toolchain go.mod declares. Alpine supplies musl
# libc: a full glibc `-static` breaks NSS/getaddrinfo, which the daemon needs for
# DNS, whereas musl static-links cleanly.
FROM golang:1.26.5-alpine AS client

# Version string injected into main.version.
ARG VERSION=dev

# build-base = gcc/g++/musl-dev plus the static libstdc++.a/libgcc.a that the
# tree-sitter C++ grammar scanners need. bash because scripts/sync-assets.sh is
# `#!/usr/bin/env bash` and uses ${BASH_SOURCE[0]}.
RUN apk add --no-cache build-base bash

WORKDIR /src

COPY . .

# The //go:embed targets are gitignored and generated by this script; a clean
# checkout has none and the build fails on the missing embed without it.
RUN ./scripts/sync-assets.sh

# CGO_ENABLED=1 with CXX=g++ so the tree-sitter grammars' scanner.cc compiles —
# tree-sitter is what powers collect/ast/file_symbols, so dropping CGO would drop
# them. -linkmode external + -extldflags fully static-link libstdc++/libgcc/musl,
# which is what makes the scratch runtime below viable.
#
# The two cache mounts are keyed DIFFERENTLY on purpose:
#   /go/pkg/mod            module SOURCE — architecture-independent, one shared id.
#   /root/.cache/go-build  compiled OBJECTS — architecture-specific, so keyed by
#                          TARGETARCH. One shared id would have arm64 and amd64
#                          evicting each other on any builder serving both.
# GOMODCACHE/GOCACHE are set explicitly so the mount targets are provably the
# paths Go actually writes; a cache mount pointed elsewhere is silently a no-op.
ARG TARGETARCH
RUN --mount=type=cache,target=/go/pkg/mod,id=gomod \
    --mount=type=cache,target=/root/.cache/go-build,id=gobuild-${TARGETARCH} \
    CGO_ENABLED=1 CC=gcc CXX=g++ GOMODCACHE=/go/pkg/mod GOCACHE=/root/.cache/go-build go build -trimpath \
      -ldflags "-linkmode external -extldflags '-static -static-libstdc++ -static-libgcc' -s -w -X main.version=${VERSION}" \
      -o /out/knowledge .

# An empty directory to seed the runtime's working directory from, so it can be
# copied in with an owner. It comes from THIS stage rather than the fetch stage
# because a local build replaces the fetch stage wholesale with a directory of
# pre-built binaries, which would not carry it.
RUN mkdir -p /out/workspace

# ---- release-binaries stage ---------------------------------------------------
# Fetches the two closed binaries from the published release for this VERSION and
# verifies them against the release's own checksums.txt.
#
# `set -eu` plus the pipeline into `sha256sum -c -` is what makes a checksum
# MISMATCH fail the build rather than warn, and the verification runs BEFORE
# `tar xzf` so a tampered tarball is never unpacked. That ordering is a gate, not
# a preference.
#
# There is deliberately no ARG for the download origin: a mutable asset source in
# a published Dockerfile is a supply-chain hazard. A local build that needs
# locally-built binaries replaces this whole stage by name instead
# (`--build-context release-binaries=<dir>`), leaving the file byte-identical.
FROM alpine:3.21 AS release-binaries
ARG VERSION
ARG TARGETARCH
RUN apk add --no-cache curl
WORKDIR /out
RUN set -eu; \
    base="https://github.com/fulminate-io/knowledge-mcp/releases/download/${VERSION}"; \
    curl -fsSL -o checksums.txt "${base}/checksums.txt"; \
    for a in knowledge-server-linux-${TARGETARCH} knowledge-frontend-linux-${TARGETARCH}; do \
      curl -fsSL -o "${a}.tar.gz" "${base}/${a}.tar.gz"; \
      grep " ${a}.tar.gz$" checksums.txt | sha256sum -c -; \
      tar xzf "${a}.tar.gz"; \
    done; \
    mv knowledge-frontend frontend; \
    mkdir -p /data/.knowledge; \
    rm -f ./*.tar.gz checksums.txt

# ---- runtime stage ------------------------------------------------------------
# scratch ships no shell, package manager, or users.
FROM scratch

# Without a trust store every outbound TLS dial inside the container fails, which
# would silently break authenticated cloud use on a base that ships none.
COPY --from=client /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt

# The client and the server MUST be siblings: the client finds the server by
# joining its own directory, which is the whole server-discovery contract.
COPY --from=client /out/knowledge /app/knowledge
COPY --from=release-binaries /out/knowledge-server /app/knowledge-server
COPY --from=release-binaries /out/frontend /app/frontend

# --chown is what makes a named volume inherit writable ownership. A BIND mount
# brings its own host ownership instead, so a bind-mounting user passes --user or
# pre-chowns the directory.
COPY --from=release-binaries --chown=65532:65532 /data /data

# /workspace is COPIED rather than left to WORKDIR because WORKDIR creates a
# directory owned by root, and the runtime user is 65532 — so anything the
# client writes into its own working directory would fail with permission
# denied. A BIND mount brings its own host ownership instead, so a bind-mounting
# user passes --user or pre-chowns the directory.
COPY --from=client --chown=65532:65532 /out/workspace /workspace

# scratch has no /etc/passwd, and Go resolves the home directory from $HOME on
# unix — the client roots ~/.knowledge through it, so HOME must land on the
# volume or every restart starts from an empty graph.
ENV HOME=/data

# Selects the login flow's container callback mode: it binds the fixed loopback
# callback port and advertises the published frontend port in its redirect URI.
# A listener bound to 127.0.0.1 inside a container is unreachable through
# `docker -p`, so the redirect has to name an address the user's browser can
# actually dial, and the frontend forwards it back in. The login container runs
# this same image, so it inherits the setting with no user action.
ENV KNOWLEDGE_LOGIN_VIA_FRONTEND=1

# The client's --root defaults to ".", so this is where a user mounts a repo.
WORKDIR /workspace

VOLUME /data
EXPOSE 15023

# Numeric nonroot uid:gid — scratch has no /etc/passwd, and the kernel only needs
# a non-zero numeric id.
USER 65532:65532

LABEL org.opencontainers.image.source="https://github.com/fulminate-io/knowledge-mcp"
LABEL io.modelcontextprotocol.server.name="io.github.fulminate-io/knowledge-mcp"

# No CMD: the front binary's own flag defaults ARE the default HTTP mode, so
# `docker run <image>` serves HTTP and `docker run -i <image> --stdio` bridges
# stdio.
ENTRYPOINT ["/app/frontend"]
