// Code generated by command: go run main.go -out ../dot_avx_amd64.s -stubs ../dot_avx_amd64.go -pkg veckernel. DO NOT EDIT.

//go:build amd64 && !veckernel_noasm

package veckernel

// dotF32AVX2 returns the dot product of the first n float32s at a and b,
// using AVX2 with FMA: six YMM accumulators over a 48-float main loop,
// then an 8-float loop, then a scalar remainder.
//
// SIX accumulators, where the AVX-512 kernel keeps four. A dot is load-
// bound rather than chain-bound once the second operand is folded into the
// FMA, and this tier's cores have three load ports against AVX-512's two,
// so four chains leave issue slots unused here that they would not there.
// Six rather than eight is a register-budget bound, not a throughput one:
// eight forces the scalar accumulator into an AVX-512-only register. See
// accsAVX2 in avogen/dot.go.
//
// n is TRUSTED. The only caller is avx2Dot, reached through DotF32, which
// has already rejected mismatched lengths and short-circuited the empty
// case — this kernel bounds-checks nothing.
//
//go:noescape
func dotF32AVX2(a *float32, b *float32, n int) float32

// dotF32AVX512 returns the dot product of the first n float32s at a and b,
// using AVX-512F: four ZMM accumulators over a 64-float main loop, then a
// 16-float loop, then a scalar remainder.
//
// FOUR accumulators, not the six the AVX2 kernel uses. Two load ports and
// a ZMM load that moves twice the bytes mean four chains already saturate
// issue; more would only lengthen the fold and add register pressure.
//
// NO AVX-512 EXTENSION BEYOND F IS NEEDED. The fold uses VEXTRACTF64X4
// rather than the AVX512DQ VEXTRACTF32X8, and the accumulators are zeroed
// with VPXORD rather than the AVX512DQ VXORPS-on-ZMM, so nothing here needs
// DQ, BW or VL. Read the exact requirement off the Requires: line avo
// emits above this function in the .s file — it also names FMA3, because
// the scalar remainder uses the VEX-encoded VFMADD231SS.
//
// n is trusted; see dotF32AVX2.
//
//go:noescape
func dotF32AVX512(a *float32, b *float32, n int) float32

// dotF32x4AVX2 scores one query against FOUR rows in a single pass using
// AVX2 with FMA, returning the four dot products.
//
// Each 16-float chunk of the query is loaded ONCE into two YMM registers
// and multiply-added against the same chunk of all four rows, so the query
// costs two loads per four distances instead of eight. The four rows are
// never loaded into registers at all: VFMADD231PS reads them straight from
// memory, which is what keeps two query registers plus eight accumulators
// inside the sixteen YMM registers amd64 has.
//
// p0..p3 are the NEXT group's rows, software-prefetched one kilobyte deep
// while this group is scored. Pass the CURRENT rows when there is no next
// group, or when dim is too small for the cap to fall inside a row — the
// prefetch then targets lines already being read and costs nothing.
//
// n is TRUSTED. avx2Gather has already been validated by DotF32Gather.
//
//go:noescape
func dotF32x4AVX2(q *float32, r0 *float32, r1 *float32, r2 *float32, r3 *float32, p0 *float32, p1 *float32, p2 *float32, p3 *float32, n int) (d0 float32, d1 float32, d2 float32, d3 float32)

// dotF32x4AVX512 scores one query against FOUR rows in a single pass using
// AVX-512F, returning the four dot products.
//
// Same fusion as dotF32x4AVX2 at twice the width: each 32-float chunk of
// the query is held in two ZMM registers across all four rows, and the rows
// are read as memory operands of VFMADD231PS.
//
// p0..p3 are the next group's rows; see dotF32x4AVX2.
//
// Needs no AVX-512 extension beyond F, for the reasons dotF32AVX512 gives;
// the Requires: line avo emits above this function in the .s file is the
// authority on the exact feature set. n is trusted.
//
//go:noescape
func dotF32x4AVX512(q *float32, r0 *float32, r1 *float32, r2 *float32, r3 *float32, p0 *float32, p1 *float32, p2 *float32, p3 *float32, n int) (d0 float32, d1 float32, d2 float32, d3 float32)
