// Code generated by command: go run main.go -out ../dot_avx_amd64.s -stubs ../dot_avx_amd64.go -pkg veckernel. DO NOT EDIT.

//go:build amd64 && !veckernel_noasm

#include "textflag.h"

// func dotF32AVX2(a *float32, b *float32, n int) float32
// Requires: AVX, FMA3, SSE
TEXT ·dotF32AVX2(SB), NOSPLIT, $0-28
	MOVQ   a+0(FP), AX
	MOVQ   b+8(FP), CX
	MOVQ   n+16(FP), DX
	VXORPS Y0, Y0, Y0
	VXORPS Y1, Y1, Y1
	VXORPS Y2, Y2, Y2
	VXORPS Y3, Y3, Y3
	VXORPS Y4, Y4, Y4
	VXORPS Y5, Y5, Y5
	VXORPS X6, X6, X6

dot_avx2_loop48:
	CMPQ        DX, $0x00000030
	JL          dot_avx2_loop8
	VMOVUPS     (AX), Y7
	VMOVUPS     32(AX), Y8
	VMOVUPS     64(AX), Y9
	VMOVUPS     96(AX), Y10
	VMOVUPS     128(AX), Y11
	VMOVUPS     160(AX), Y12
	VFMADD231PS (CX), Y7, Y0
	VFMADD231PS 32(CX), Y8, Y1
	VFMADD231PS 64(CX), Y9, Y2
	VFMADD231PS 96(CX), Y10, Y3
	VFMADD231PS 128(CX), Y11, Y4
	VFMADD231PS 160(CX), Y12, Y5
	ADDQ        $0x000000c0, AX
	ADDQ        $0x000000c0, CX
	SUBQ        $0x00000030, DX
	JMP         dot_avx2_loop48

dot_avx2_loop8:
	CMPQ        DX, $0x00000008
	JL          dot_avx2_loop1
	VMOVUPS     (AX), Y7
	VFMADD231PS (CX), Y7, Y0
	ADDQ        $0x00000020, AX
	ADDQ        $0x00000020, CX
	SUBQ        $0x00000008, DX
	JMP         dot_avx2_loop8

dot_avx2_loop1:
	TESTQ       DX, DX
	JE          dot_avx2_reduce
	VMOVSS      (AX), X7
	VFMADD231SS (CX), X7, X6
	ADDQ        $0x00000004, AX
	ADDQ        $0x00000004, CX
	DECQ        DX
	JMP         dot_avx2_loop1

dot_avx2_reduce:
	VADDPS       Y1, Y0, Y0
	VADDPS       Y3, Y2, Y2
	VADDPS       Y5, Y4, Y4
	VADDPS       Y2, Y0, Y0
	VADDPS       Y4, Y0, Y0
	VEXTRACTF128 $0x01, Y0, X1
	VADDPS       X1, X0, X0
	VHADDPS      X0, X0, X0
	VHADDPS      X0, X0, X0
	VADDSS       X6, X0, X0
	VZEROUPPER
	MOVSS        X0, ret+24(FP)
	RET

// func dotF32AVX512(a *float32, b *float32, n int) float32
// Requires: AVX, AVX512F, FMA3, SSE
TEXT ·dotF32AVX512(SB), NOSPLIT, $0-28
	MOVQ   a+0(FP), AX
	MOVQ   b+8(FP), CX
	MOVQ   n+16(FP), DX
	VPXORD Z0, Z0, Z0
	VPXORD Z1, Z1, Z1
	VPXORD Z2, Z2, Z2
	VPXORD Z3, Z3, Z3
	VXORPS X4, X4, X4

dot_avx512_loop64:
	CMPQ        DX, $0x00000040
	JL          dot_avx512_loop16
	VMOVUPS     (AX), Z5
	VMOVUPS     64(AX), Z6
	VMOVUPS     128(AX), Z7
	VMOVUPS     192(AX), Z8
	VFMADD231PS (CX), Z5, Z0
	VFMADD231PS 64(CX), Z6, Z1
	VFMADD231PS 128(CX), Z7, Z2
	VFMADD231PS 192(CX), Z8, Z3
	ADDQ        $0x00000100, AX
	ADDQ        $0x00000100, CX
	SUBQ        $0x00000040, DX
	JMP         dot_avx512_loop64

dot_avx512_loop16:
	CMPQ        DX, $0x00000010
	JL          dot_avx512_loop1
	VMOVUPS     (AX), Z5
	VFMADD231PS (CX), Z5, Z0
	ADDQ        $0x00000040, AX
	ADDQ        $0x00000040, CX
	SUBQ        $0x00000010, DX
	JMP         dot_avx512_loop16

dot_avx512_loop1:
	TESTQ       DX, DX
	JE          dot_avx512_reduce
	VMOVSS      (AX), X5
	VFMADD231SS (CX), X5, X4
	ADDQ        $0x00000004, AX
	ADDQ        $0x00000004, CX
	DECQ        DX
	JMP         dot_avx512_loop1

dot_avx512_reduce:
	VADDPS        Z1, Z0, Z0
	VADDPS        Z3, Z2, Z2
	VADDPS        Z2, Z0, Z0
	VEXTRACTF64X4 $0x01, Z0, Y1
	VADDPS        Y1, Y0, Y0
	VEXTRACTF128  $0x01, Y0, X1
	VADDPS        X1, X0, X0
	VHADDPS       X0, X0, X0
	VHADDPS       X0, X0, X0
	VADDSS        X4, X0, X0
	VZEROUPPER
	MOVSS         X0, ret+24(FP)
	RET

// func dotF32x4AVX2(q *float32, r0 *float32, r1 *float32, r2 *float32, r3 *float32, p0 *float32, p1 *float32, p2 *float32, p3 *float32, n int) (d0 float32, d1 float32, d2 float32, d3 float32)
// Requires: AVX, FMA3, MMX+, SSE
TEXT ·dotF32x4AVX2(SB), NOSPLIT, $0-96
	MOVQ   q+0(FP), AX
	MOVQ   r0+8(FP), CX
	MOVQ   r1+16(FP), DX
	MOVQ   r2+24(FP), BX
	MOVQ   r3+32(FP), SI
	MOVQ   p0+40(FP), DI
	MOVQ   p1+48(FP), R8
	MOVQ   p2+56(FP), R9
	MOVQ   p3+64(FP), R10
	MOVQ   n+72(FP), R11
	VXORPS Y0, Y0, Y0
	VXORPS Y1, Y1, Y1
	VXORPS X2, X2, X2
	VXORPS Y3, Y3, Y3
	VXORPS Y4, Y4, Y4
	VXORPS X5, X5, X5
	VXORPS Y6, Y6, Y6
	VXORPS Y7, Y7, Y7
	VXORPS X8, X8, X8
	VXORPS Y9, Y9, Y9
	VXORPS Y10, Y10, Y10
	VXORPS X11, X11, X11
	MOVQ   $0x00000010, R12

gather4_avx2_loop16:
	CMPQ       R11, $0x00000010
	JL         gather4_avx2_loop8
	TESTQ      R12, R12
	JZ         gather4_avx2_pfdone
	PREFETCHT0 (DI)
	PREFETCHT0 (R8)
	PREFETCHT0 (R9)
	PREFETCHT0 (R10)
	ADDQ       $0x00000040, DI
	ADDQ       $0x00000040, R8
	ADDQ       $0x00000040, R9
	ADDQ       $0x00000040, R10
	DECQ       R12

gather4_avx2_pfdone:
	VMOVUPS     (AX), Y12
	VMOVUPS     32(AX), Y13
	VFMADD231PS (CX), Y12, Y0
	VFMADD231PS 32(CX), Y13, Y1
	VFMADD231PS (DX), Y12, Y3
	VFMADD231PS 32(DX), Y13, Y4
	VFMADD231PS (BX), Y12, Y6
	VFMADD231PS 32(BX), Y13, Y7
	VFMADD231PS (SI), Y12, Y9
	VFMADD231PS 32(SI), Y13, Y10
	ADDQ        $0x00000040, AX
	ADDQ        $0x00000040, CX
	ADDQ        $0x00000040, DX
	ADDQ        $0x00000040, BX
	ADDQ        $0x00000040, SI
	SUBQ        $0x00000010, R11
	JMP         gather4_avx2_loop16

gather4_avx2_loop8:
	CMPQ        R11, $0x00000008
	JL          gather4_avx2_loop1
	VMOVUPS     (AX), Y12
	VFMADD231PS (CX), Y12, Y0
	VFMADD231PS (DX), Y12, Y3
	VFMADD231PS (BX), Y12, Y6
	VFMADD231PS (SI), Y12, Y9
	ADDQ        $0x00000020, AX
	ADDQ        $0x00000020, CX
	ADDQ        $0x00000020, DX
	ADDQ        $0x00000020, BX
	ADDQ        $0x00000020, SI
	SUBQ        $0x00000008, R11
	JMP         gather4_avx2_loop8

gather4_avx2_loop1:
	TESTQ       R11, R11
	JE          gather4_avx2_reduce
	VMOVSS      (AX), X12
	VFMADD231SS (CX), X12, X2
	VFMADD231SS (DX), X12, X5
	VFMADD231SS (BX), X12, X8
	VFMADD231SS (SI), X12, X11
	ADDQ        $0x00000004, AX
	ADDQ        $0x00000004, CX
	ADDQ        $0x00000004, DX
	ADDQ        $0x00000004, BX
	ADDQ        $0x00000004, SI
	DECQ        R11
	JMP         gather4_avx2_loop1

gather4_avx2_reduce:
	VADDPS       Y1, Y0, Y0
	VEXTRACTF128 $0x01, Y0, X1
	VADDPS       X1, X0, X0
	VHADDPS      X0, X0, X0
	VHADDPS      X0, X0, X0
	VADDSS       X2, X0, X0
	VADDPS       Y4, Y3, Y3
	VEXTRACTF128 $0x01, Y3, X1
	VADDPS       X1, X3, X1
	VHADDPS      X1, X1, X1
	VHADDPS      X1, X1, X1
	VADDSS       X5, X1, X1
	VADDPS       Y7, Y6, Y6
	VEXTRACTF128 $0x01, Y6, X2
	VADDPS       X2, X6, X2
	VHADDPS      X2, X2, X2
	VHADDPS      X2, X2, X2
	VADDSS       X8, X2, X2
	VADDPS       Y10, Y9, Y9
	VEXTRACTF128 $0x01, Y9, X3
	VADDPS       X3, X9, X3
	VHADDPS      X3, X3, X3
	VHADDPS      X3, X3, X3
	VADDSS       X11, X3, X3
	VZEROUPPER
	MOVSS        X0, d0+80(FP)
	MOVSS        X1, d1+84(FP)
	MOVSS        X2, d2+88(FP)
	MOVSS        X3, d3+92(FP)
	RET

// func dotF32x4AVX512(q *float32, r0 *float32, r1 *float32, r2 *float32, r3 *float32, p0 *float32, p1 *float32, p2 *float32, p3 *float32, n int) (d0 float32, d1 float32, d2 float32, d3 float32)
// Requires: AVX, AVX512F, FMA3, MMX+, SSE
TEXT ·dotF32x4AVX512(SB), NOSPLIT, $0-96
	MOVQ   q+0(FP), AX
	MOVQ   r0+8(FP), CX
	MOVQ   r1+16(FP), DX
	MOVQ   r2+24(FP), BX
	MOVQ   r3+32(FP), SI
	MOVQ   p0+40(FP), DI
	MOVQ   p1+48(FP), R8
	MOVQ   p2+56(FP), R9
	MOVQ   p3+64(FP), R10
	MOVQ   n+72(FP), R11
	VPXORD Z0, Z0, Z0
	VPXORD Z1, Z1, Z1
	VXORPS X2, X2, X2
	VPXORD Z3, Z3, Z3
	VPXORD Z4, Z4, Z4
	VXORPS X5, X5, X5
	VPXORD Z6, Z6, Z6
	VPXORD Z7, Z7, Z7
	VXORPS X8, X8, X8
	VPXORD Z9, Z9, Z9
	VPXORD Z10, Z10, Z10
	VXORPS X11, X11, X11
	MOVQ   $0x00000008, R12

gather4_avx512_loop32:
	CMPQ       R11, $0x00000020
	JL         gather4_avx512_loop16
	TESTQ      R12, R12
	JZ         gather4_avx512_pfdone
	PREFETCHT0 (DI)
	PREFETCHT0 64(DI)
	PREFETCHT0 (R8)
	PREFETCHT0 64(R8)
	PREFETCHT0 (R9)
	PREFETCHT0 64(R9)
	PREFETCHT0 (R10)
	PREFETCHT0 64(R10)
	ADDQ       $0x00000080, DI
	ADDQ       $0x00000080, R8
	ADDQ       $0x00000080, R9
	ADDQ       $0x00000080, R10
	DECQ       R12

gather4_avx512_pfdone:
	VMOVUPS     (AX), Z12
	VMOVUPS     64(AX), Z13
	VFMADD231PS (CX), Z12, Z0
	VFMADD231PS 64(CX), Z13, Z1
	VFMADD231PS (DX), Z12, Z3
	VFMADD231PS 64(DX), Z13, Z4
	VFMADD231PS (BX), Z12, Z6
	VFMADD231PS 64(BX), Z13, Z7
	VFMADD231PS (SI), Z12, Z9
	VFMADD231PS 64(SI), Z13, Z10
	ADDQ        $0x00000080, AX
	ADDQ        $0x00000080, CX
	ADDQ        $0x00000080, DX
	ADDQ        $0x00000080, BX
	ADDQ        $0x00000080, SI
	SUBQ        $0x00000020, R11
	JMP         gather4_avx512_loop32

gather4_avx512_loop16:
	CMPQ        R11, $0x00000010
	JL          gather4_avx512_loop1
	VMOVUPS     (AX), Z12
	VFMADD231PS (CX), Z12, Z0
	VFMADD231PS (DX), Z12, Z3
	VFMADD231PS (BX), Z12, Z6
	VFMADD231PS (SI), Z12, Z9
	ADDQ        $0x00000040, AX
	ADDQ        $0x00000040, CX
	ADDQ        $0x00000040, DX
	ADDQ        $0x00000040, BX
	ADDQ        $0x00000040, SI
	SUBQ        $0x00000010, R11
	JMP         gather4_avx512_loop16

gather4_avx512_loop1:
	TESTQ       R11, R11
	JE          gather4_avx512_reduce
	VMOVSS      (AX), X12
	VFMADD231SS (CX), X12, X2
	VFMADD231SS (DX), X12, X5
	VFMADD231SS (BX), X12, X8
	VFMADD231SS (SI), X12, X11
	ADDQ        $0x00000004, AX
	ADDQ        $0x00000004, CX
	ADDQ        $0x00000004, DX
	ADDQ        $0x00000004, BX
	ADDQ        $0x00000004, SI
	DECQ        R11
	JMP         gather4_avx512_loop1

gather4_avx512_reduce:
	VADDPS        Z1, Z0, Z0
	VEXTRACTF64X4 $0x01, Z0, Y1
	VADDPS        Y1, Y0, Y0
	VEXTRACTF128  $0x01, Y0, X1
	VADDPS        X1, X0, X0
	VHADDPS       X0, X0, X0
	VHADDPS       X0, X0, X0
	VADDSS        X2, X0, X0
	VADDPS        Z4, Z3, Z3
	VEXTRACTF64X4 $0x01, Z3, Y1
	VADDPS        Y1, Y3, Y1
	VEXTRACTF128  $0x01, Y1, X2
	VADDPS        X2, X1, X1
	VHADDPS       X1, X1, X1
	VHADDPS       X1, X1, X1
	VADDSS        X5, X1, X1
	VADDPS        Z7, Z6, Z6
	VEXTRACTF64X4 $0x01, Z6, Y2
	VADDPS        Y2, Y6, Y2
	VEXTRACTF128  $0x01, Y2, X3
	VADDPS        X3, X2, X2
	VHADDPS       X2, X2, X2
	VHADDPS       X2, X2, X2
	VADDSS        X8, X2, X2
	VADDPS        Z10, Z9, Z9
	VEXTRACTF64X4 $0x01, Z9, Y3
	VADDPS        Y3, Y9, Y3
	VEXTRACTF128  $0x01, Y3, X4
	VADDPS        X4, X3, X3
	VHADDPS       X3, X3, X3
	VHADDPS       X3, X3, X3
	VADDSS        X11, X3, X3
	VZEROUPPER
	MOVSS         X0, d0+80(FP)
	MOVSS         X1, d1+84(FP)
	MOVSS         X2, d2+88(FP)
	MOVSS         X3, d3+92(FP)
	RET
