// SPDX-License-Identifier: Apache-2.0

// files_scope_test.go — the FILE-LIST scope, at the analyzer, where all four
// caller faces converge.
//
// THE PROPERTY UNDER TEST IS NOT "the named files were scanned". It is that NO
// NAMED FILE IS EVER ABSENT FROM THE REPORT: every path the caller writes is
// scanned, disclosed by name, or refused by name, and never silently dropped
// into a clean verdict. Two walk filters would otherwise drop diff files without
// a word — discovery's exclusion rules take a generated file, and the walk's own
// test-file filter takes a _test.go — so the rows below drive both.
//
// Every row goes through the analyzer's Extra map rather than through a helper
// that builds the scope directly, because the map IS the channel the tool, the
// CLI and the topology dispatcher all reach it by.

package corpusscan

import (
	"encoding/json"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/fulminate-io/knowledge-mcp/internal/topology/foundation"
)

// generatedGo carries the header discovery's skip_generated_go rule keys on,
// plus a real site, so a run that opens it flags and a run that declines it is
// silently clean.
const generatedGo = `// Code generated by a tool. DO NOT EDIT.

package p

type c struct{}

func (c) Close() error { return nil }

func use(x c) {
	defer x.Close()
}
`

// filesRepo is the tree every row below names paths in. Each Go file holds one
// site for the shared defer-Close check, so a site count is attributable to the
// files that were opened.
func filesRepo(t *testing.T) string {
	t.Helper()
	return seedRepo(t, map[string]string{
		"lib/a.go":       deferCloseBad,
		"lib/b.go":       deferCloseBad,
		"lib/a_test.go":  deferCloseBad,
		"other/c.go":     deferCloseBad,
		"lib/clean.go":   knownNegative,
		"docs/readme.md": "# docs\n",
		"gen/api.pb.go":  generatedGo,
	})
}

// withFiles returns req carrying the file-list scope, encoded the way every
// caller face encodes it.
func withFiles(req foundation.Request, paths ...string) foundation.Request {
	if req.Extra == nil {
		req.Extra = map[string]string{}
	}
	raw, err := json.Marshal(paths)
	if err != nil {
		panic(err)
	}
	req.Extra[ExtraKeyFiles] = string(raw)
	return req
}

// withRawFiles returns req carrying a VERBATIM Extra value, for the malformed
// encodings a well-formed marshal can never produce.
func withRawFiles(req foundation.Request, raw string) foundation.Request {
	if req.Extra == nil {
		req.Extra = map[string]string{}
	}
	req.Extra[ExtraKeyFiles] = raw
	return req
}

// defersCorpus is the one-check corpus every ast row here runs.
func defersCorpus() *fakeCaller {
	return astCorpus(checkNode("chk-1", "no naked defer Close", "handle the error Close returns",
		astCheckMeta("defer $X.Close()", "warning", "fx-bad", "fx-good")))
}

// TestCorpusScan_FileScopeScansExactlyTheNamedFiles is the scope's own property,
// with the unnarrowed run as the control: without it, "the narrowed run flagged
// one" is also what a broken scope that always scanned a single file produces.
func TestCorpusScan_FileScopeScansExactlyTheNamedFiles(t *testing.T) {
	root := filesRepo(t)
	gc := defersCorpus()

	// CONTROL: unnarrowed, the walk reaches every non-test, non-generated file.
	whole := siteFiles(runScan(t, scanRequest(gc, "repo", root)))
	if len(whole) != 3 {
		t.Fatalf("control: the unnarrowed walk must flag lib/a.go, lib/b.go and other/c.go, got %v", whole)
	}

	got := siteFiles(runScan(t, withFiles(scanRequest(gc, "repo", root), "lib/a.go", "other/c.go")))
	if len(got) != 2 || got[0] != "lib/a.go" || got[1] != "other/c.go" {
		t.Fatalf("a file list must scan exactly the paths it names, got %v", got)
	}
}

// TestCorpusScan_FileScopeRefusesMalformedInput walks every parse arm. The
// control is a well-formed list, so a parser that refused everything could not
// satisfy these rows.
func TestCorpusScan_FileScopeRefusesMalformedInput(t *testing.T) {
	root := filesRepo(t)
	gc := defersCorpus()

	// CONTROL: a well-formed list is answered.
	if err := runScanErr(withFiles(scanRequest(gc, "repo", root), "lib/a.go")); err != nil {
		t.Fatalf("control: a well-formed file list must scan, got %v", err)
	}

	// EACH ROW ASSERTS ITS OWN REASON, not merely that something was refused.
	// Several of these arms sit behind one another — an absolute path is also a
	// path that does not resolve under the root, and a dot-dot path is also
	// unclean — so a row that asserted only "refused, naming the value" stayed
	// GREEN with its own guard deleted, satisfied by the next guard down. The
	// reason string is what makes each guard independently observed.
	for _, tc := range []struct {
		name, raw, want, reason string
	}{
		{"present but empty", "", ExtraKeyFiles, "present but empty"},
		{"whitespace only", "   ", ExtraKeyFiles, "present but empty"},
		{"empty array", "[]", ExtraKeyFiles, "present but empty"},
		{"not json", "lib/a.go", ExtraKeyFiles, "does not decode"},
		{"json but not an array", `"lib/a.go"`, ExtraKeyFiles, "does not decode"},
		{"empty element", `["lib/a.go",""]`, "2", "is empty"},
		{"absolute path", `["/etc/passwd"]`, "/etc/passwd", "an absolute path"},
		{"dot dot", `["lib/../../escape.go"]`, "escape.go", "escapes the repo"},
		{"leading dot slash", `["./lib/a.go"]`, "./lib/a.go", "not the spelling the walk compares against"},
		{"trailing slash", `["lib/a.go/"]`, "lib/a.go/", "not the spelling the walk compares against"},
		{"doubled separator", `["lib//a.go"]`, "lib//a.go", "not the spelling the walk compares against"},
		{"absent from the tree", `["lib/nosuch.go"]`, "lib/nosuch.go", "does not resolve"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			err := runScanErr(withRawFiles(scanRequest(gc, "repo", root), tc.raw))
			if err == nil {
				t.Fatalf("%q must be refused rather than scanned, coerced or silently dropped", tc.raw)
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Errorf("the refusal must name the offending value %q, got %q", tc.want, err)
			}
			if !strings.Contains(err.Error(), tc.reason) {
				t.Errorf("the refusal must state THIS arm's reason %q — a neighboring guard catching it instead leaves this one unobserved; got %q", tc.reason, err)
			}
		})
	}
}

// TestCorpusScan_FileScopeAndPathPrefixAreMutuallyExclusive: both lower to the
// same walk channel, so accepting both would mean "these files AND that whole
// subtree" and make the per-path accounting unanswerable.
func TestCorpusScan_FileScopeAndPathPrefixAreMutuallyExclusive(t *testing.T) {
	root := filesRepo(t)
	req := withFiles(scanRequest(defersCorpus(), "repo", root), "lib/a.go")
	req.PathPrefix = "lib"
	err := runScanErr(req)
	if err == nil {
		t.Fatal("supplying both scope params must be refused, never silently resolved to one of them")
	}
	for _, want := range []string{ExtraKeyFiles, "path_prefix"} {
		if !strings.Contains(err.Error(), want) {
			t.Errorf("the refusal must name both params; %q is missing from %q", want, err)
		}
	}
}

// TestCorpusScan_FileScopeRefusesAnUnreadableNamedFile is the class WalkStats
// cannot name: a file that EXISTS and cannot be opened lands in a by-cause
// counter with no path beside it, so the guard has to run before the walk.
func TestCorpusScan_FileScopeRefusesAnUnreadableNamedFile(t *testing.T) {
	if os.Geteuid() == 0 {
		t.Skip("running as root: a mode-000 file is readable, so this class cannot be constructed here")
	}
	root := filesRepo(t)
	locked := filepath.Join(root, "lib", "locked.go")
	if err := os.WriteFile(locked, []byte(deferCloseBad), 0o000); err != nil {
		t.Fatalf("write the unreadable fixture: %v", err)
	}

	err := runScanErr(withFiles(scanRequest(defersCorpus(), "repo", root), "lib/locked.go"))
	if err == nil {
		t.Fatal("a named file that cannot be opened must be refused, never reported clean over a file nobody read")
	}
	if !strings.Contains(err.Error(), "lib/locked.go") {
		t.Errorf("the refusal must NAME the path — a count of unopened files sends nobody anywhere, got %q", err)
	}
	// AND IT MUST GIVE THIS ARM'S REASON. Without the reason the assertion above
	// is satisfied by the zero-scan refusal, which echoes the whole named list
	// back and so contains the path incidentally — leaving the pre-walk resolve
	// unobserved while the suite stayed green.
	if !strings.Contains(err.Error(), "cannot be opened") {
		t.Errorf("the refusal must say the file could not be OPENED — a downstream guard naming the path for another reason leaves this one unobserved; got %q", err)
	}
}

// TestCorpusScan_FileScopeOpensFilesTheWalkWouldDecline drives both hazard
// classes the ticket's no-silent-drop clause exists for.
func TestCorpusScan_FileScopeOpensFilesTheWalkWouldDecline(t *testing.T) {
	root := filesRepo(t)
	gc := defersCorpus()

	t.Run("a named test file is scanned", func(t *testing.T) {
		// CONTROL: the same file under the default run-wide scope is NOT reached,
		// which is what makes the row above a property of the file list.
		if got := siteFiles(runScan(t, scanRequest(gc, "repo", root))); contains(got, "lib/a_test.go") {
			t.Fatalf("control: the default walk must skip test files, got %v", got)
		}
		got := siteFiles(runScan(t, withFiles(scanRequest(gc, "repo", root), "lib/a_test.go")))
		if len(got) != 1 || got[0] != "lib/a_test.go" {
			t.Fatalf("a named test file must be OPENED — the alternative is a clean verdict over a file nobody read, got %v", got)
		}
	})

	t.Run("a named generated file is scanned", func(t *testing.T) {
		if got := siteFiles(runScan(t, scanRequest(gc, "repo", root))); contains(got, "gen/api.pb.go") {
			t.Fatalf("control: discovery's own rule must decline a generated file by default, got %v", got)
		}
		got := siteFiles(runScan(t, withFiles(scanRequest(gc, "repo", root), "gen/api.pb.go")))
		if len(got) != 1 || got[0] != "gen/api.pb.go" {
			t.Fatalf("a named generated file must be OPENED: the caller named it, which overrides discovery's guess, got %v", got)
		}
	})

	t.Run("an explicit include_tests=false alongside a named test file is refused", func(t *testing.T) {
		req := withIncludeTests(withFiles(scanRequest(gc, "repo", root), "lib/a_test.go"), "false")
		err := runScanErr(req)
		if err == nil {
			t.Fatal("the caller asked for two incompatible things and bad input errors rather than picking one")
		}
		if !strings.Contains(err.Error(), "lib/a_test.go") {
			t.Errorf("the refusal must name the file that makes it a contradiction, got %q", err)
		}
	})
}

// TestCorpusScan_FileScopeDisclosesOtherLanguagePaths: a real diff carries
// markdown, and the corpus is one language by construction — so the path is
// dropped from the walk and NAMED in the report.
func TestCorpusScan_FileScopeDisclosesOtherLanguagePaths(t *testing.T) {
	root := filesRepo(t)
	findings := runScan(t, withFiles(scanRequest(defersCorpus(), "repo", root), "lib/a.go", "docs/readme.md"))

	disclosure := findingsByTitlePrefix(findings, DisclosureTitleOtherLanguage)
	if len(disclosure) != 1 {
		t.Fatalf("a dropped path must be disclosed exactly once, got %d", len(disclosure))
	}
	if !strings.Contains(strings.Join(disclosure[0].Evidence, " "), "docs/readme.md") {
		t.Errorf("the disclosure must NAME the dropped path, got %v", disclosure[0].Evidence)
	}
	if got := siteFiles(findings); len(got) != 1 || got[0] != "lib/a.go" {
		t.Errorf("and the run proceeds over the rest, got %v", got)
	}
	// THE DISCLOSURE IS NOT A FLAGGED SITE. A title the verdict fold does not
	// recognize counts as one, which would make every mixed diff read FLAGGED.
	if v := ClassifyRun(findings); v.SitesFlagged != 1 {
		t.Errorf("the disclosure must not be counted as a flagged site, got sites_flagged=%d", v.SitesFlagged)
	}
}

// TestCorpusScan_FileScopeThatOpenedNothingIsRefused is the vacuous-green closer
// on THIS channel. The run-level guard used to be keyed on a non-empty
// path_prefix alone, so a file-list run whose checks opened nothing rendered a
// verdict instead of refusing.
func TestCorpusScan_FileScopeThatOpenedNothingIsRefused(t *testing.T) {
	root := filesRepo(t)

	// CONTROL: the same channel with a Go file named IS answered, so the refusal
	// below is about the scope reaching nothing rather than about file lists.
	if err := runScanErr(withFiles(scanRequest(defersCorpus(), "repo", root), "lib/a.go")); err != nil {
		t.Fatalf("control: a file list that reaches a file must scan, got %v", err)
	}

	err := runScanErr(withFiles(scanRequest(defersCorpus(), "repo", root), "docs/readme.md"))
	if err == nil {
		t.Fatal("every named file dropped means the check opened nothing, and a scan that opened no file is not a clean scan")
	}
	if !strings.Contains(err.Error(), "chk-1") {
		t.Errorf("the refusal names the check that scanned nothing, got %q", err)
	}
}

// TestCorpusScan_FileScopeNamesAPathTheWalkDidNotOpen is the post-walk backstop.
//
// IT IS PORTABLE ACROSS BOTH FILESYSTEM FLAVORS ON PURPOSE. A wrong-case path
// resolves on a case-INsensitive filesystem (macOS) and reaches the walk, where
// the prefix predicate compares bytes and drops it — that is the shortfall the
// backstop exists for. On a case-SENSITIVE filesystem the pre-walk resolve
// refuses it as absent. Either way the caller is told, by name, and that is the
// property: no named path is ever absent from the report.
func TestCorpusScan_FileScopeNamesAPathTheWalkDidNotOpen(t *testing.T) {
	root := filesRepo(t)
	err := runScanErr(withFiles(scanRequest(defersCorpus(), "repo", root), "lib/a.go", "lib/A.go"))
	if err == nil {
		t.Fatal("a named path the walk never opened must be refused rather than folded into a verdict")
	}
	if !strings.Contains(err.Error(), "lib/A.go") && !strings.Contains(err.Error(), "named file(s)") {
		t.Errorf("the refusal must name the path, or report the shortfall and its by-cause counters, got %q", err)
	}
}

// TestCorpusScan_FileScopeCarriesEveryByteAPathCanHold pins the encoding
// decision. A comma join would split the first path below into two that do not
// exist; the caller would then read a refusal naming values they never wrote.
func TestCorpusScan_FileScopeCarriesEveryByteAPathCanHold(t *testing.T) {
	root := seedRepo(t, map[string]string{
		"lib/a,b.go":   deferCloseBad,
		"lib/plain.go": deferCloseBad,
	})
	gc := defersCorpus()
	got := siteFiles(runScan(t, withFiles(scanRequest(gc, "repo", root), "lib/a,b.go")))
	if len(got) != 1 || got[0] != "lib/a,b.go" {
		t.Fatalf("a comma-bearing path is a path the walk accepts and the encoding must carry it, got %v", got)
	}
}

// TestCorpusScan_FileScopeIsDeterministicAndAgreesWithThePrefixChannel pins the
// two state properties: the same list twice is the same answer, and a list
// naming every file under a subtree flags exactly what that subtree flags.
func TestCorpusScan_FileScopeIsDeterministicAndAgreesWithThePrefixChannel(t *testing.T) {
	root := filesRepo(t)
	gc := defersCorpus()

	first := siteFiles(runScan(t, withFiles(scanRequest(gc, "repo", root), "lib/a.go", "lib/b.go")))
	second := siteFiles(runScan(t, withFiles(scanRequest(gc, "repo", root), "lib/a.go", "lib/b.go")))
	if strings.Join(first, ",") != strings.Join(second, ",") {
		t.Fatalf("the walk is deterministic and the render is sorted, so two runs must agree: %v vs %v", first, second)
	}

	prefixReq := scanRequest(gc, "repo", root)
	prefixReq.PathPrefix = "lib"
	viaPrefix := siteFiles(runScan(t, prefixReq))
	viaFiles := siteFiles(runScan(t, withFiles(scanRequest(gc, "repo", root), "lib/a.go", "lib/b.go", "lib/clean.go")))
	if strings.Join(viaPrefix, ",") != strings.Join(viaFiles, ",") {
		t.Errorf("naming every file of a subtree must flag exactly what the subtree flags: %v vs %v", viaPrefix, viaFiles)
	}
}

// TestCorpusScan_FileScopeCountsADuplicateOnce: the same path twice is one file,
// and the accounting must not read the repetition as a file the walk missed.
func TestCorpusScan_FileScopeCountsADuplicateOnce(t *testing.T) {
	root := filesRepo(t)
	got := siteFiles(runScan(t, withFiles(scanRequest(defersCorpus(), "repo", root), "lib/a.go", "lib/a.go")))
	if len(got) != 1 || got[0] != "lib/a.go" {
		t.Fatalf("a repeated path is one file, scanned once and counted once, got %v", got)
	}
}

// TestCorpusScan_FileScopeAdmitsADirectoryAsThePrefixItIs: ast.Scope's own
// prefix semantics make no distinction between a file and a directory, and
// neither does this.
func TestCorpusScan_FileScopeAdmitsADirectoryAsThePrefixItIs(t *testing.T) {
	root := filesRepo(t)
	got := siteFiles(runScan(t, withFiles(scanRequest(defersCorpus(), "repo", root), "other")))
	if len(got) != 1 || got[0] != "other/c.go" {
		t.Fatalf("a named directory is the prefix it is, not an error, got %v", got)
	}
}

// contains reports whether xs holds s.
func contains(xs []string, s string) bool {
	return slices.Contains(xs, s)
}

// TestCorpusScan_FileScopeScansANewlineBearingPath closes the carrier's other
// end: the CLI face proves a newline-bearing path reaches the tool byte-identical,
// and this proves the analyzer OPENS it.
//
// WHY THE NEWLINE AND NOT ONLY THE COMMA. The comma row above covers what a
// comma-separated carrier would split; a newline is what a LINE-oriented one
// would split, and a filesystem accepts it and the walk scans it. Without this
// row the JSON encoding is justified by an argument rather than by a file.
func TestCorpusScan_FileScopeScansANewlineBearingPath(t *testing.T) {
	const weird = "lib/we\nird.go"
	root := seedRepo(t, map[string]string{
		weird:          deferCloseBad,
		"lib/other.go": deferCloseBad,
	})
	gc := defersCorpus()

	// CONTROL: unnarrowed, the walk reaches both files — so the file is scannable
	// at all and a zero below would be the scope rather than the filesystem.
	if got := len(siteFiles(runScan(t, scanRequest(gc, "repo", root)))); got != 2 {
		t.Fatalf("control: the unnarrowed walk must reach both files, got %d", got)
	}

	got := siteFiles(runScan(t, withFiles(scanRequest(gc, "repo", root), weird)))
	if len(got) != 1 || got[0] != weird {
		t.Fatalf("a named path carrying a newline must be scanned under exactly that name, got %q", got)
	}
}
