// SPDX-License-Identifier: Apache-2.0

package tools

import "github.com/fulminate-io/knowledge-mcp/internal/kgtools"

// ManageToolDef returns the unified manage tool definition.
//
// The MCP tool catalog is client-owned: loadSchemas composes this def into
// tools/list. Pure kgtools.MCPTool literal.
func ManageToolDef() kgtools.MCPTool {
	return kgtools.MCPTool{
		Name: "manage",
		Description: "Unified server and graph lifecycle management tool. " +
			"status: show graph stats plus a per-graph durable LLM-coverage table (total / summarized / embedded / summary-fail / embed-fail per sync-eligible graph); the pipeline runtime counters in the same output are process-lifetime (reset on restart / clear_llm_failures), NOT durable coverage. " +
			"pprof_start / pprof_stop: bracket a CPU profile of the knowledge client (where collectors run). pprof_start lazily brings up the loopback pprof endpoint (127.0.0.1:15021); pprof_stop returns a URL to fetch the profile (go tool pprof http://127.0.0.1:15021/debug/pprof/capture). Both are handled client-side by the knowledge binary. " +
			"delete_branch: remove a branch overlay index. list_branches: list indexed branch overlays. " +
			"link: run cross-graph linking (the Dockerfile COPY signal) to create code-to-code edges. " +
			"set_metadata_overrides: replace the per-graph OverrideConfig for metadata keys (force_scalar pins keys to the inline map; force_edge pins keys to value-node edges). " +
			"Requires graph=<type> and name=<graph identifier> for non-knowledge graphs. Both force_scalar and force_edge accept JSON arrays; at least one must be non-empty. " +
			"migrate_embed_identity: change a graph's RECORDED embed identity to the named profile's — the ONLY operation that does. It records the new identity, CLEARS the vectors the superseded identity produced (so the graph never holds two vector widths, which the image serializer refuses), re-opens every cleared node so the pipeline re-embeds it, and prunes the superseded cache rows. It reports how many vectors it cleared, because that count IS the re-embedding bill about to be paid. Requires graph + name + profile. " +
			"promote_metadata: refresh per-graph metadata cardinality stats then iterate every key and dispatch PromoteKey/DemoteKey via ApplyDecision based on the current hysteresis bands (or, with force=true, the simple distinct<1000 rule that bypasses hysteresis — operator one-shot only). " +
			"Requires graph=<practice or a registered custom graph type> and name=<graph identifier>. dry_run=true returns the action report without writing. " +
			"Use this immediately after the metadata-promotion subsystem ships to backfill existing graphs, or on demand when an operator wants to flip representations without waiting for the dream PROMOTE timer. " +
			"clear_llm_failures: clear summary_failure_reason and embed_failure_reason metadata on every node across one or all loaded graphs so the LLM pipeline collector re-discovers them on the next tick. Operator recovery path for terminally-failed nodes (4xx-other / context-too-large / config error). With graph= and name= empty, walks every loaded graph; with graph= set, scopes to that graph type; with both set, scopes to one named graph. " +
			"pipeline_status: report whether the LLM summary/embed pipeline is RUNNING or latched PAUSED, with the pause reason and the resume instruction. The search staleness footer also surfaces the paused state loudly. " +
			"pause_pipeline: manually latch BOTH the summary and embed worker pools paused (global, in-memory) with an optional reason=; the workers stop pulling new batches until resumed. " +
			"resume_pipeline: clear the paused latch and wake the workers. It is the ONLY exit from a circuit-break trip — the pipeline auto-pauses after a full error round (every LLM call erroring with zero successes, e.g. a quota/auth wall or repeated timeouts) and stays paused with NO self-heal until resume_pipeline is run. All pause/resume state is in-memory and cleared on restart. " +
			"prune: hard-delete (garbage-collect) tombstoned nodes from a graph. Works generically on ANY graph type (knowledge, code, practice, web, pdf, linkage, checks) — it is 'delete tombstoned nodes,' nothing more, with no graph-type allowlist. Requires a non-empty graph (name it explicitly). before=<relative window like '24h'/'2d' OR absolute RFC3339> deletes only tombstones tombstoned before that cutoff; omit before to prune ALL tombstoned nodes. Returns the pruned count, plus a WARNING line when the sweep completed but something after it degraded (e.g. the persist that follows the commit) — a warning is a PARTIAL SUCCESS, not a failure: the nodes are gone and the removal has already propagated, so read the warning and continue rather than retrying the prune. " +
			"prune-cache: ONE-TIME reclaim of orphaned client-side L2 search segments — the superseded .seg blobs the invalidation-driven reclaim never unlinked. It enumerates the segment-bearing graphs (knowledge/default + every code repo) and, per graph+format, force-full-loads the engine so the live set is COMPLETE (an unloaded-but-live segment is never false-pruned), then diffs the on-disk ids against that complete live set and removes the orphans. The completeness of the live set IS the whole safety: a bare Export from an engine that has loaded nothing is EMPTY, and diffing against an empty live set would condemn every segment on disk. PREVIEWS by default (reports the would-remove orphans per graph+format, deletes nothing); execute=true performs the removal. Not periodic — a one-shot backlog sweep. " +
			"rebuild_cache: DROP a code repo's per-repo content-hash caches (summary + embed) and RE-DERIVE them from the CURRENT base-graph nodes with ZERO model calls — a FREE re-derivation, NOT a 'clear' (a clear would guarantee a full re-pay for LLM/Voyage). The caches let a merged-and-recollected node reuse the summary/embedding it earned on a branch overlay. Use it for recovery (lost/corrupted cache), manual invalidation (the model/prompt-change lever), or backfill/migration (graphs populated before the feature shipped, so branch work benefits immediately). Requires graph=code (name=repo) or graph=knowledge (name defaults to 'default', BASE layer only — no '@'-overlay names in v1); practice and registered custom types are not supported. ASYNC: the server drops + re-derives the caches on a background goroutine and returns a STARTED acknowledgement immediately (a large graph's walk would otherwise exceed the edge timeout). Confirm completion via the server logs (\"rebuild_cache.complete\"). " +
			"rebuild_segments: BACKFILL a code repo's BM25+HNSW search segments from nodes that are ALREADY embedded but have ZERO built segments (embedded before the segment build path existed, or after a segment-cache prune) — WITHOUT re-embedding. The server is engine-free, so the WORK is CLIENT-driven: the client pages the already-embedded nodes (with their stored vector + server-composed BM25 fields), rebuilds the segments DETERMINISTICALLY (fixed seed + serial-within / concurrent-across), and writes them to its LOCAL segment cache. Requires graph=code (or the builtin knowledge graph, or a registered custom graph type) + name; for graph=knowledge the name defaults to 'default' (its one canonical instance) and only the BASE layer is supported (an '@'-suffixed overlay name is rejected in v1). Single-flight per (graph,name). IDEMPOTENT: a deterministic build makes a re-run over an unchanged node set a byte-identical content-hash-diffed NO-OP (the first rebuild over an embed-segmented graph ships the deterministic segments and prunes the superseded embed ones; every rebuild after is a no-op). Runs SYNCHRONOUSLY and reports the scanned/built/pruned counts. " +
			"register_repo: record a repo name → absolute checkout directory in the machine-local manifest (~/.knowledge/repos.json) — the same registry a code collect populates. Purely client-side (the path is machine-specific and never leaves this host) and idempotent (re-registering a name overwrites its path). Lets a cross-repo ast walk resolve a bare repo name to its real directory without collecting the repo first. Requires name + root (an existing absolute directory). " +
			"drop_graph: tear down a WHOLE graph (the persisted store plus its loaded state) via one DROP_GRAPH mutation. Requires graph=<knowledge|code|web|pdf|checks|linkage or a registered custom type> plus the instance field that family requires (code→name as repo, the rest→name; knowledge needs no name). graph=practice is REFUSED: a practice graph is never a destructive target, and to remove a set of practice nodes you delete them by their source hub instead. DESTRUCTIVE: the default EXECUTES the drop; dry_run=true issues ZERO mutations and renders a 'would drop' preview so you can confirm the target first. " +
			"repair_edges: ONE-SHOT operator repair for CONTAINS fossils — file-to-symbol edges whose target symbol lives in a DIFFERENT file than the file node claiming it. A re-collect never repairs them: the collect path replaces a source node's edge set only from the collect forward, so an edge landed under a wrong source stays resident no matter how many times the repo is re-collected. PREVIEWS by default (enumerates and reports counts per graph, mutating nothing); execute=true removes the enumerated edges and nothing else. Requires graph=code plus name=<repo> to scope to one repo, or graph=code with an empty name to sweep every code graph. " +
			"A repair covers the base graph AND every branch overlay of each targeted repo, because the reads an operator verifies with auto-stamp the checkout's branch and consult the overlay stack; branch=<name> narrows it to exactly that one overlay (branch requires name). The empty-name cloud execute sweep stays REFUSED — a named repo plus all its overlays is a legitimate scoped sweep, an unnamed one is not. An operator one-shot, never automatic. " +
			"import_style_rules: import a generic RULE-LIST file of code style rules as PRACTICE NODES under one language hub. The file is JSON: a top-level object with a `rules` array, each rule carrying name, summary, text and severity (info/notice/warning/critical), plus an optional scope {repo, paths[]}, an optional linter {name, rule_id}, an optional check {dsl_pattern, check_where, fixture_bad, fixture_good} and an optional id. It writes practice nodes and NOTHING ELSE: no check node, no fixture node, and no sister_check cross-link — a sister check is authored later by its own manage_checks(create) call, after an LLM pass on the practice node, and a rule's check block rides its practice node as inert data until then. The whole list lands in ONE create_batch so every rule gets its hub metadata key and its sourced-from edge atomically; a rule whose id already exists is UPDATED per field rather than re-created, so re-importing the same list produces no duplicate and clears no field. Every refusal names the rule's index in the file: a missing name, summary or text, a severity off the ladder, a scope path that is absolute or carries a `..` segment or is not the repo-relative spelling, an unknown key at any level, and a duplicate id within one file. dry_run=true validates and reports without writing. " +
			"Required params by operation (in addition to the always-required operation): " +
			"delete_branch / list_branches require name + branch; " +
			"migrate_embed_identity requires graph + name + profile; set_metadata_overrides / promote_metadata require graph + name; prune requires graph; prune-cache requires nothing further (it enumerates knowledge/default + every code repo itself) and previews by default, deleting only on execute:true; rebuild_cache requires graph=code or graph=knowledge + name (for graph=knowledge the name defaults to 'default', base layer only); rebuild_segments requires graph=code or graph=knowledge (or a registered custom graph type) + name (for graph=knowledge the name defaults to 'default', base layer only); drop_graph requires graph (plus the family instance field);" +
			"pause_pipeline accepts an optional reason; resume_pipeline / pipeline_status require nothing further; " +
			"register_repo requires name + root; " +
			"import_style_rules requires source (the hub id) + path (an absolute path to the rule-list JSON); " +
			"status / link / clear_llm_failures / pprof_start / pprof_stop require nothing further.",
		InputSchema: kgtools.InputSchema{
			Type: "object",
			Properties: map[string]kgtools.Property{
				"operation":    {Type: "string", Description: "Operation to perform", Enum: []string{"status", "pprof_start", "pprof_stop", "delete_branch", "list_branches", "link", "set_metadata_overrides", "promote_metadata", "migrate_embed_identity", "clear_llm_failures", "pause_pipeline", "resume_pipeline", "pipeline_status", "prune", "prune-cache", "rebuild_cache", "rebuild_segments", "drop_graph", "register_repo", "repair_edges", "import_style_rules"}},
				"graph":        {Type: "string", Description: "Target graph type for clear_llm_failures (knowledge, code, practice)"},
				"name":         {Type: "string", Description: "Graph instance name (the repo name to record for register_repo; the repo / account / language / name the target family is keyed by elsewhere)"},
				"branch":       {Type: "string", Description: "Branch name (for delete_branch, list_branches). For repair_edges: repair ONLY that one branch overlay of name — branch REQUIRES name (branch with an empty name is an error), and the value is the BARE overlay name ('launch-fixes'), though the composed catalog key ('myrepo@launch-fixes') is accepted and normalized. Omit branch and a repair covers the base graph AND every branch overlay of each targeted repo."},
				"root":         {Type: "string", Description: "Absolute checkout directory for register_repo"},
				"source":       {Type: "string", Description: "For import_style_rules: the id of the `source` hub node every imported rule is grouped under. Spelled `source` rather than `source_hub` because the name is free on this schema — the practice hub selector publishes `source` wherever it is free and `source_hub` only on the arms (mutate, search) where `source` already means something else."},
				"path":         {Type: "string", Description: "For import_style_rules: an ABSOLUTE path to the rule-list JSON file. A relative path would resolve against the daemon's working directory rather than the caller's, so it is refused rather than guessed at."},
				"profile":      {Type: "string", Description: "For migrate_embed_identity: the name of the embedder profile to migrate the graph TO. Must name a profile the config defines ([embedder.profile.<name>], or \"default\" for the single [embedder] table); an unknown name is refused naming the defined profiles."},
				"keys":         {Type: "string", Description: "For promote_metadata: comma-separated metadata key filter. Only the named keys are considered for promotion/demotion; empty means every key the stats snapshot observed."},
				"format":       {Type: "string", Description: "Output format: 'text' (default) or 'json' (structured)"},
				"force_scalar": {Type: "array", Items: &kgtools.Property{Type: "string"}, Description: "Metadata keys pinned to the scalar map for set_metadata_overrides. Replaces the existing list."},
				"force_edge":   {Type: "array", Items: &kgtools.Property{Type: "string"}, Description: "Metadata keys pinned to value-node edges for set_metadata_overrides. Replaces the existing list."},
				"dry_run":      {Type: "boolean", Description: "For promote_metadata: when true, run the decision pass and report intended actions without mutating the graph. For drop_graph: when true, render a 'would drop' preview and issue ZERO mutations. Default false (executes)."},
				"force":        {Type: "boolean", Description: "For promote_metadata: when true, bypass the hysteresis bands and use the simple distinct<1000 rule. Operator one-shot path only."},
				"execute":      {Type: "boolean", Description: "For prune-cache: when true, DELETE the orphaned segments; default false renders a would-remove preview only. For repair_edges: when true, REMOVE the enumerated cross-file CONTAINS fossils; default false renders the preview only."},
				"before":       {Type: "string", Description: "For prune: cutoff for which tombstoned nodes to hard-delete. A relative window ('24h', '2d') or an absolute RFC3339 timestamp; only tombstones tombstoned before it are pruned. Omit to prune ALL tombstoned nodes."},
				"reason":       {Type: "string", Description: "For pause_pipeline: optional operator reason surfaced by pipeline_status. Defaults to a generic 'manually paused by operator' string when omitted."},
				"reset":        {Type: "boolean", Description: "For rebuild_segments: when true, ignore the stored watermark and rebuild the WHOLE corpus. Default false scans only what changed since the last rebuild that landed."},
			},
			Required: []string{"operation"},
		},
	}
}
