// SPDX-License-Identifier: Apache-2.0

package logs

import (
	"testing"
	"time"

	wirelogs "github.com/fulminate-io/knowledge-mcp/internal/logwire"
)

func TestIsGoStackFragment(t *testing.T) {
	tests := []struct {
		name string
		tpl  wirelogs.LogTemplate
		want bool
	}{
		{"goroutine header", wirelogs.LogTemplate{Pattern: "goroutine 42 [running]:"}, true},
		{"register dump", wirelogs.LogTemplate{Pattern: "rax    0xc000123456"}, true},
		{"go file line", wirelogs.LogTemplate{Pattern: "  /usr/local/go/src/runtime/panic.go:1038"}, true},
		{"runtime function", wirelogs.LogTemplate{Pattern: "runtime.gopanic(0xc000123456)"}, true},
		{"created by", wirelogs.LogTemplate{Pattern: "created by runtime.init.6"}, true},
		{"segment register gs", wirelogs.LogTemplate{Pattern: "gs     0x0"}, true},
		{"flags register", wirelogs.LogTemplate{Pattern: "rflags 0x212"}, true},
		{"instruction pointer", wirelogs.LogTemplate{Pattern: "rip    0x40daee"}, true},
		{"assembly file", wirelogs.LogTemplate{Pattern: "  /usr/local/go/src/internal/runtime/syscall/asm_linux_amd64.s:36 +0xe"}, true},
		{"net stdlib", wirelogs.LogTemplate{Pattern: "net.(*Dialer).DialContext(0xc00003c7e0, ...)"}, true},
		{"signal info", wirelogs.LogTemplate{Pattern: "PC=0x40daee m=10 sigcode=18446744073709551610"}, true},
		{"SIGABRT", wirelogs.LogTemplate{Pattern: "SIGABRT: abort"}, true},
		{"autogenerated", wirelogs.LogTemplate{Pattern: "  <autogenerated>:1 +0x49 fp=0xc0005859c0"}, true},
		{"main.main", wirelogs.LogTemplate{Pattern: "main.main()"}, true},
		{"PC offset only", wirelogs.LogTemplate{Pattern: "  /some/path/file.go:42 +0x1a3"}, true},
		{"prefixed with >", wirelogs.LogTemplate{Pattern: "\t>  github.com/go-logr/logr.Logger.Info({})"}, true},
		// ExampleVars-based detection.
		{"example vars match", wirelogs.LogTemplate{
			Pattern:     "<*>",
			ExampleVars: [][]string{{"goroutine 99 [running]:"}},
		}, true},
		// False positives must NOT match.
		{"normal log", wirelogs.LogTemplate{Pattern: "connection timeout after 3200ms"}, false},
		{"normal error", wirelogs.LogTemplate{Pattern: "Error exporting metrics to UAS"}, false},
		{"k8s audit json", wirelogs.LogTemplate{Pattern: `{"annotations":"allow"}`}, false},
		{"k8s warning log", wirelogs.LogTemplate{Pattern: `W0227 18:04:49.468376      12 dispatcher.go:210] Failed`}, false},
		{"timestamped", wirelogs.LogTemplate{Pattern: `2026-02-27 18:47:01 UTC connection reset`}, false},
		{"logrus", wirelogs.LogTemplate{Pattern: `time="2026-02-27T18:01:01Z" level=info msg="ok"`}, false},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := isGoStackFragment(&tt.tpl); got != tt.want {
				t.Errorf("isGoStackFragment(%q) = %v, want %v", tt.tpl.Pattern, got, tt.want)
			}
		})
	}
}

func TestGoStackConsolidator(t *testing.T) {
	c := &goStackConsolidator{}
	now := time.Now()

	t.Run("merges goroutine dump fragments", func(t *testing.T) {
		templates := []*wirelogs.LogTemplate{
			{Pattern: "connection timeout", Severity: wirelogs.SeverityError, Count: 5,
				FirstSeen: now, LastSeen: now.Add(10 * time.Second)},
			{Pattern: "goroutine 1 [running]:", Severity: wirelogs.SeverityError, Count: 1,
				FirstSeen: now, LastSeen: now},
			{Pattern: "runtime.gopanic(0xc000)", Severity: wirelogs.SeverityError, Count: 1,
				FirstSeen: now, LastSeen: now.Add(100 * time.Millisecond)},
			{Pattern: "rax    0xc000123456", Severity: wirelogs.SeverityError, Count: 1,
				FirstSeen: now, LastSeen: now.Add(200 * time.Millisecond)},
			{Pattern: "rbx    0x00000000", Severity: wirelogs.SeverityError, Count: 1,
				FirstSeen: now, LastSeen: now.Add(200 * time.Millisecond)},
			{Pattern: "  /usr/local/go/src/runtime/panic.go:1038", Severity: wirelogs.SeverityError, Count: 1,
				FirstSeen: now, LastSeen: now.Add(300 * time.Millisecond)},
			{Pattern: "created by runtime.init.6", Severity: wirelogs.SeverityError, Count: 1,
				FirstSeen: now, LastSeen: now.Add(400 * time.Millisecond)},
		}

		result := c.Consolidate(templates)

		if len(result) != 2 {
			t.Fatalf("expected 2 templates, got %d", len(result))
		}
		if result[0].Pattern != "connection timeout" {
			t.Errorf("first template should be normal, got %q", result[0].Pattern)
		}

		crash := result[1]
		if crash.Pattern != "Go runtime crash (goroutine dump)" {
			t.Errorf("merged pattern: got %q", crash.Pattern)
		}
		if crash.Count != 6 {
			t.Errorf("merged count: got %d, want 6", crash.Count)
		}
		if crash.Severity != wirelogs.SeverityCritical {
			t.Errorf("merged severity: got %s, want %s", crash.Severity, wirelogs.SeverityCritical)
		}
		if len(crash.ExampleVars) == 0 {
			t.Error("merged crash should have at least 1 example")
		}
	})

	t.Run("fewer than 3 fragments left as-is", func(t *testing.T) {
		templates := []*wirelogs.LogTemplate{
			{Pattern: "normal log", Severity: wirelogs.SeverityInfo, Count: 10,
				FirstSeen: now, LastSeen: now},
			{Pattern: "goroutine 1 [running]:", Severity: wirelogs.SeverityError, Count: 1,
				FirstSeen: now, LastSeen: now},
			{Pattern: "runtime.gopanic()", Severity: wirelogs.SeverityError, Count: 1,
				FirstSeen: now, LastSeen: now},
		}

		result := c.Consolidate(templates)

		if len(result) != 3 {
			t.Fatalf("expected 3 templates (no consolidation), got %d", len(result))
		}
	})

	t.Run("temporally separated crashes stay separate", func(t *testing.T) {
		templates := []*wirelogs.LogTemplate{
			{Pattern: "goroutine 1 [running]:", Severity: wirelogs.SeverityError, Count: 1,
				FirstSeen: now, LastSeen: now},
			{Pattern: "rax    0xc000123456", Severity: wirelogs.SeverityError, Count: 1,
				FirstSeen: now, LastSeen: now.Add(100 * time.Millisecond)},
			{Pattern: "  /usr/local/go/src/runtime/panic.go:1038", Severity: wirelogs.SeverityError, Count: 1,
				FirstSeen: now, LastSeen: now.Add(200 * time.Millisecond)},
			{Pattern: "goroutine 99 [running]:", Severity: wirelogs.SeverityError, Count: 1,
				FirstSeen: now.Add(60 * time.Second), LastSeen: now.Add(60 * time.Second)},
			{Pattern: "rbx    0x00000000", Severity: wirelogs.SeverityError, Count: 1,
				FirstSeen: now.Add(60 * time.Second), LastSeen: now.Add(60100 * time.Millisecond)},
			{Pattern: "created by main.init", Severity: wirelogs.SeverityError, Count: 1,
				FirstSeen: now.Add(60 * time.Second), LastSeen: now.Add(60200 * time.Millisecond)},
		}

		result := c.Consolidate(templates)

		crashCount := 0
		for _, tpl := range result {
			if tpl.Pattern == "Go runtime crash (goroutine dump)" {
				crashCount++
			}
		}
		if crashCount != 2 {
			t.Errorf("expected 2 crash templates, got %d", crashCount)
		}
	})
}
