// SPDX-License-Identifier: Apache-2.0

package logs

import (
	"regexp"
	"slices"
	"sort"
	"strings"
	"time"

	wirelogs "github.com/fulminate-io/knowledge-mcp/internal/logwire"
)

type goStackConsolidator struct{}

func (g *goStackConsolidator) Name() string { return "go_stack" }

// Consolidate detects Go goroutine dump fragments, groups them by temporal
// proximity (30s window), and merges groups of 3+ into single CRITICAL
// templates.
func (g *goStackConsolidator) Consolidate(templates []*wirelogs.LogTemplate) []*wirelogs.LogTemplate {
	var fragments []*wirelogs.LogTemplate
	var normal []*wirelogs.LogTemplate

	for _, t := range templates {
		if isGoStackFragment(t) {
			fragments = append(fragments, t)
		} else {
			normal = append(normal, t)
		}
	}

	if len(fragments) < 3 {
		return templates
	}

	sort.Slice(fragments, func(i, j int) bool {
		return fragments[i].LastSeen.Before(fragments[j].LastSeen)
	})

	groups := groupByTime(fragments, 30*time.Second)

	for _, group := range groups {
		if len(group) < 3 {
			normal = append(normal, group...)
			continue
		}
		normal = append(normal, mergeGoStackGroup(group))
	}

	return normal
}

// mergeGoStackGroup merges a temporal group of Go stack fragments into a
// single CRITICAL template.
func mergeGoStackGroup(group []*wirelogs.LogTemplate) *wirelogs.LogTemplate {
	merged := &wirelogs.LogTemplate{
		Pattern:   "Go runtime crash (goroutine dump)",
		Severity:  wirelogs.SeverityCritical,
		FirstSeen: group[0].FirstSeen,
		LastSeen:  group[0].LastSeen,
	}

	for _, t := range group {
		merged.Count += t.Count
		if t.FirstSeen.Before(merged.FirstSeen) {
			merged.FirstSeen = t.FirstSeen
		}
		if t.LastSeen.After(merged.LastSeen) {
			merged.LastSeen = t.LastSeen
		}
		if wirelogs.SeverityIndex(t.Severity) > wirelogs.SeverityIndex(merged.Severity) {
			merged.Severity = t.Severity
		}
		if len(merged.ExampleVars) < 3 {
			if reGoStack.MatchString(t.Pattern) || reExceptionHeader.MatchString(t.Pattern) {
				ex := t.Pattern
				if len(t.ExampleVars) > 0 {
					ex = strings.Join(t.ExampleVars[0], " ")
				}
				merged.ExampleVars = append(merged.ExampleVars, []string{ex})
			}
		}
	}

	if len(merged.ExampleVars) == 0 {
		if len(group[0].ExampleVars) > 0 {
			merged.ExampleVars = [][]string{group[0].ExampleVars[0]}
		} else {
			merged.ExampleVars = [][]string{{group[0].Pattern}}
		}
	}

	merged.Alias = TemplateAliasFor(merged)
	return merged
}

// groupByTime splits a time-sorted slice of templates into groups where
// consecutive templates are within the given window.
func groupByTime(sorted []*wirelogs.LogTemplate, window time.Duration) [][]*wirelogs.LogTemplate {
	if len(sorted) == 0 {
		return nil
	}
	var groups [][]*wirelogs.LogTemplate
	current := []*wirelogs.LogTemplate{sorted[0]}

	for i := 1; i < len(sorted); i++ {
		prevEnd := current[len(current)-1].LastSeen
		if sorted[i].FirstSeen.Sub(prevEnd) <= window {
			current = append(current, sorted[i])
		} else {
			groups = append(groups, current)
			current = []*wirelogs.LogTemplate{sorted[i]}
		}
	}
	return append(groups, current)
}

// Go stack trace detection regexes.
var (
	reGoFuncCall     = regexp.MustCompile(`^[\w.*/()\-:]+\.\w+\(`)
	reGoStackArgs    = regexp.MustCompile(`\((0x[0-9a-fA-F]|\.\.\.|\{\}|\)|\{0x|[0-9a-fA-F]+\?|0x)`)
	reGoSourceRef    = regexp.MustCompile(`\.go:\d+`)
	reGoSSourceRef   = regexp.MustCompile(`\.s:\d+`)
	reGoPCOffset     = regexp.MustCompile(`\+0x[0-9a-fA-F]+`)
	reGoRegisterDump = regexp.MustCompile(
		`^(rax|rbx|rcx|rdx|rsi|rdi|rbp|rsp|r[89]|r1[0-5]|eax|ebx|ecx|edx|` +
			`gs|fs|cs|rflags|eflags|rip|eip)\s+0x`)
	reGoCreatedBy     = regexp.MustCompile(`^created by\s+`)
	reGoSignalInfo    = regexp.MustCompile(`^(PC=0x|SIG[A-Z]+[: ]|signal )`)
	reGoAutogenerated = regexp.MustCompile(`^<autogenerated>:\d+`)
)

func isGoStackFragment(t *wirelogs.LogTemplate) bool {
	return matchesGoStackPattern(t.Pattern) ||
		exampleVarsContain(t.ExampleVars, matchesGoStackPattern)
}

// exampleVarsContain returns true if any ExampleVars row (joined) matches fn.
func exampleVarsContain(vars [][]string, fn func(string) bool) bool {
	return slices.ContainsFunc(vars, func(row []string) bool {
		return fn(strings.Join(row, " "))
	})
}

func normalizeStackLine(msg string) string {
	msg = strings.TrimLeft(msg, " \t")
	msg = strings.TrimPrefix(msg, ">")
	return strings.TrimLeft(msg, " \t")
}

func matchesGoStackPattern(msg string) bool {
	norm := normalizeStackLine(msg)
	if len(norm) == 0 {
		return false
	}

	// Never match JSON objects, arrays, or structured log lines.
	if norm[0] == '{' || norm[0] == '[' {
		return false
	}
	// Reject timestamped log entries.
	if len(norm) > 4 && norm[0] >= '0' && norm[0] <= '9' && norm[4] == '-' {
		return false
	}
	if strings.HasPrefix(norm, "time=") || strings.HasPrefix(norm, "ts=") {
		return false
	}
	// Reject long prose without Go markers.
	if len(norm) > 300 && !reGoSourceRef.MatchString(norm) && !reGoPCOffset.MatchString(norm) {
		return false
	}

	return matchesHighConfidence(norm) || matchesSourceRef(norm) || matchesFuncCall(norm)
}

// matchesHighConfidence checks patterns that are unambiguously Go stack frames.
func matchesHighConfidence(norm string) bool {
	return reGoStack.MatchString(norm) ||
		reGoRegisterDump.MatchString(norm) ||
		reGoCreatedBy.MatchString(norm) ||
		reGoSignalInfo.MatchString(norm) ||
		reGoAutogenerated.MatchString(norm)
}

// matchesSourceRef checks for .go:NNN or .s:NNN source file references
// that look like stack frame lines (not K8s log lines).
func matchesSourceRef(norm string) bool {
	if reGoSourceRef.MatchString(norm) && len(norm) < 200 {
		if reGoPCOffset.MatchString(norm) {
			return true
		}
		trimmed := strings.TrimLeft(norm, " \t")
		if len(trimmed) > 0 && trimmed[0] == '/' {
			return true
		}
	}
	if reGoSSourceRef.MatchString(norm) && len(norm) < 200 {
		if reGoPCOffset.MatchString(norm) {
			return true
		}
		trimmed := strings.TrimLeft(norm, " \t")
		if len(trimmed) > 0 && trimmed[0] == '/' {
			return true
		}
	}
	return false
}

// matchesFuncCall checks for Go function call patterns with stack-like args.
func matchesFuncCall(norm string) bool {
	return reGoFuncCall.MatchString(norm) && len(norm) < 300 && reGoStackArgs.MatchString(norm)
}
