// SPDX-License-Identifier: Apache-2.0

package segmentdist

// measurement_gate_test.go holds the opt-in gate for this package's HNSW-BUILDING
// tests, and the classification rule that decides which tests those are.
//
// The rule is stated here rather than in the package doc comment (manager.go)
// because it is a fact about this package's TESTS, not about the layer they cover,
// and this package's own convention is a file-level block under the package clause
// (testkit_shared_test.go does the same).
//
// WHY THE HEAVY TESTS ARE OPT-IN. Roughly nine tenths of this package's CPU is HNSW
// index construction, and it buys nothing that a small corpus does not: the tests
// that build 1024 documents or more assert layering, bucketing, rebuild and reclaim
// BEHAVIOUR, not build throughput. Measured over the whole package on one machine,
// removing them takes it from 657 CPU-seconds to 34-47 while the assertions they
// make are unchanged. They are therefore a MEASUREMENT SUITE, run deliberately, and
// they skip loudly the rest of the time.
//
// ENV-GATED, NOT BUILD-TAG-GATED, following veckernel's PerfEnv and the ast
// package's AST_PEAK_CONTROL: a file behind a build tag is one the linter never
// compiles unless every lint invocation is told about that tag, and a pass that
// silently skips files reports success having checked nothing.
//
// ===========================================================================
// THE CLASSIFICATION RULE
// ===========================================================================
//
// 1. THE RULE. A test is HEAVY, and is gated, if it builds an HNSW corpus of
// searchengine.DefaultMinSegmentDocs documents or more, directly or through a
// fixture helper. The rule cites the CONSTANT and never the literal 1024, so a
// change to the segment-sizing default moves the rule with it.
//
// 2. THE FORMAT DIMENSION, WHICH IS THE CONSUMING LEG AND NOT THE DOCUMENT SHAPE.
// vecContentDocsSeed, bothFormatDocs, overlayBaseDocs and searchCorpus all set
// Vector on every document; whether an HNSW segment is BUILT depends on which arm
// receives the slice.
//
// THE LEG LIST IS REGENERATED BY THE CENSUS RATHER THAN MAINTAINED HERE. An earlier
// round of this work maintained a hand list of four legs; it was missing two, and
// one of the two was the ONLY route a member of the set had. TestMeasurementGate-
// Census derives the table from this package's own non-test source on every run and
// fails when a Manager method that consumes a document slice is left unclassified.
// The list below is what that derivation currently returns, recorded so a reader
// knows the shape, NOT as the census's input:
//
//	HNSW legs:  AddAndMarkDirty, ReplaceBucket, ReEmitRebuiltDelta, and
//	            StageRebuildPartition PAIRED WITH FinalizeRebuild — the pair is ONE
//	            leg, because staging only appends BucketWork under mu and builds
//	            nothing until the finalize takes it; plus the engine primitives
//	            engine.Add and engine.AddSealAndSupersede and the test helper
//	            seedShipped.
//	BM25 legs:  AddAndMarkDirtyFields, ReplaceBucketFields with its private
//	            replaceBucketFields, and the test helper seedShippedFields.
//
// FOUR CAVEAT CLASSES, because the next author will meet all four:
//
//	(i)   TWO LEGS TAKE BOTH SLICES. ReEmitRebuiltDelta and StageRebuildPartition
//	      each accept an hnsw slice and a bm25 slice and route each to its own arm,
//	      so the question is which PARAMETER a corpus is passed as, never merely
//	      which method was called.
//	(ii)  ONE SINK ROUTES ON A BOOLEAN. recordDirty selects &st.hnsw or &st.bm25 on
//	      its `fields` parameter, so it has no static arm and is not a leg in its
//	      own right.
//	(iii) A HELPER'S NAME LIES. stageBM25Reset delegates to stageRebuildRun, whose
//	      body passes THE SAME slice into both of StageRebuildPartition's document
//	      parameters, so a helper named for BM25 builds HNSW too — which is why both
//	      of manager_rebuild_bm25_test.go's tests are gated.
//	(iv)  NAMING THE ENGINE PRIMITIVES NARROWS THE PAST-THE-MANAGER CLASS, IT DOES
//	      NOT CLOSE IT. A build can sit one call past the Manager entirely: tests
//	      call replaceBucketAndPublish directly, and sealPerPartition and sealOne are
//	      generic helpers that a walk over func shapes cannot see at all. The census
//	      therefore derives its legs from the BUILD SINKS those helpers are, resolved
//	      through their arm-bound callers, rather than from a list of method names.
//
// 3. THE TWO REJECTED ALTERNATIVES, both tried and both wrong:
//
//	A DURATION THRESHOLD. "Three seconds or more" named 56, 63 and 72 tests across
//	three runs of ONE unchanged tree, differing only by what else the machine was
//	doing. A set that moves with ambient load is not a classification.
//
//	READING "BUILDS A REAL HNSW SEGMENT" LITERALLY. bothFormatDocs(2) seals a real
//	HNSW segment and costs hundredths of a second. The cost is in the corpus size,
//	which is why the rule names one.
//
// 4. THE BM25-ONLY NEAR-MISS CLASS, WHICH IS ELEVEN, and is correctly ungated.
// Eleven tests build a corpus at or above the threshold and stay in the regular run
// because their corpus reaches the FIELD leg alone: TestMergedL2FileCarriesThe-
// Envelope, TestL2AndResidencyAccountingCountTheWholeFile, TestStaleMergeScratchIs-
// SweptBeforeEachMerge, TestAMergeScratchSweepFailureIsTheMergesError, partition-
// Fixture's three callers (TestWriteSealsOneSegmentPerPartition, TestWriteSeals-
// PartitionsInADeterministicOrder, TestResidentDeleteDoesNotWidenPastItsPartition),
// and four in manager_search_overlay_test.go (TestSearchOverlayRanksByComparable-
// Scores, TestSearchOverlayFallsBackWhenOverlayPoolEmpty, TestSearchOverlayPool-
// Errors, TestSearchOverlayAbsentTokenYieldsNoOverlayDomination).
//
// THE SHARPEST ILLUSTRATION is a pair inside one file over one 1024-document
// fixture: TestSearchOverlayRanksByComparableScores (field leg only) at 0.04-0.56 s
// against TestSearchOverlayFusesHNSWArmAcrossPools (both legs) at 5.09-11.92 s.
// Same documents, two orders of magnitude, one call apart.
//
// A THIRD REASON FOR BEING UNGATED, distinct from both the rule and the format leg:
// TestSearchOverlayAdmitsBaseAndOverlay drives a COLD manager with no shipped
// segments and asserts admission recording, so it builds no corpus at all.

import (
	"fmt"
	"os"
	"strings"
	"testing"

	"github.com/fulminate-io/knowledge-mcp/internal/searchengine"
)

// segmentdistMeasureEnv gates every HNSW-BUILDING test in this package. Set it to 1
// and they run; leave it unset and they SKIP, so an ordinary `go test` over this
// package exercises the fast set only.
//
// INERT UNLESS SET TO EXACTLY "1". The gate is a boolean and it owns no other
// behaviour: it supplies no path, no size and no seed, so an unset variable costs
// one skip per gated test and nothing else.
const segmentdistMeasureEnv = "SEGMENTDIST_MEASURE"

// segmentdistMeasureTarget is the make target that sets the variable. It is named in
// the skip message so a reader of a skipped run learns how to take the measurement
// without going to find out.
//
// THIS NAME IS MAINTAINED BY HAND AND NO TEST OBSERVES THAT THE TARGET EXISTS. The
// assertions in TestRequireMeasurementRunArms prove the skip message still MENTIONS
// this constant; they cannot prove the constant still names something real. Rename or
// delete the Makefile target and every gated test keeps telling an operator to run a
// command that answers "No rule to make target", with the suite green. Whoever
// renames it renames this line in the same change.
//
// THE OTHER HALF OF THE SAME CONTRACT IS TESTED, which is why only this half carries
// a warning: the VARIABLE name is checked by the target's own MEASUREMENT DID NOT RUN
// guard, which fails the run when the recipe's literal and this package's constant
// disagree.
//
// WHY NOT READ THE MAKEFILE HERE, which is the obvious fix and is deliberately not
// taken. This package is shipped to the public OSS mirror, and the mirror RE-ROOTS it:
// scripts/sync-to-oss.sh copies cmd/knowledge/internal to the mirror's top-level
// internal/, so this file lives at internal/segmentdist/ there rather than at
// cmd/knowledge/internal/segmentdist/. A relative walk up to this repository's root
// resolves ABOVE the mirror's root, and the read fails for every consumer who runs the
// shipped tests. The mirror ships no Makefile at that path either. A shipped test that
// reads above its own module root is exactly the coupling the mirror is being cleaned
// of, so adding one here to check a documentation string is the wrong trade, and the
// unverified name is recorded as the accepted cost rather than left unsaid.
const segmentdistMeasureTarget = "make measure-segmentdist"

// requireMeasurementRun skips unless segmentdistMeasureEnv is set to exactly "1".
//
// EXACTLY "1" rather than any non-empty value, for the reason veckernel's envEnabled
// gives: an operator who exports the variable as 0 in order to turn the gate OFF
// must not thereby have turned it on. "0", "true", "yes" and "" all skip.
//
// THE SKIP IS LOUD ON PURPOSE. It names the variable, the target that sets it, and
// what went unmeasured — a skip that reads like a pass is the failure this gate
// would otherwise introduce, because 78 tests going quiet is exactly the shape of a
// suite that has stopped covering something.
//
// IT IS THE FIRST STATEMENT OF EVERY GATED TEST so a skipped run costs nothing: no
// corpus is generated, no manager is built and no temporary directory is written.
func requireMeasurementRun(t *testing.T) {
	t.Helper()
	if os.Getenv(segmentdistMeasureEnv) != "1" {
		t.Skip(measurementSkipMessage())
	}
}

// measurementSkipMessage is the skip text, built here rather than inline so a test
// can assert what it names. A SKIP MESSAGE IS READ BY MACHINES as well as by people:
// landed acceptance criteria grep `--- PASS: <name> ` lines, and a package that exits
// 0 while 78 tests quietly skip is exactly the shape those criteria cannot see.
func measurementSkipMessage() string {
	return fmt.Sprintf("HNSW BUILD NOT MEASURED: this test builds an HNSW corpus of %d documents or more, "+
		"which is index-construction cost rather than the behaviour under test, so it is opt-in. "+
		"Set %s=1, or run `%s`, to run it. The fast tests in this package still ran.",
		searchengine.DefaultMinSegmentDocs, segmentdistMeasureEnv, segmentdistMeasureTarget)
}

// TestRequireMeasurementRunArms pins the gate's own behaviour, one arm per value an
// operator can plausibly set.
//
// THE "0" ARM IS THE ONE THAT MATTERS. A gate keyed on "is the variable non-empty"
// turns ON when someone exports it as 0 to turn it OFF, which is why this accepts
// exactly "1" — and why that acceptance is pinned here rather than left to the
// helper's comment.
//
// THE PROBE CAPTURES THE INNER T because t.Skip unwinds the goroutine it is called
// on: the closure cannot report its own outcome, so the captured pointer is read
// after t.Run returns.
func TestRequireMeasurementRunArms(t *testing.T) {
	for _, tc := range []struct {
		name     string
		set      bool
		value    string
		wantSkip bool
	}{
		{name: "unset", set: false, wantSkip: true},
		{name: "one_runs", set: true, value: "1", wantSkip: false},
		{name: "zero_skips", set: true, value: "0", wantSkip: true},
		{name: "true_skips", set: true, value: "true", wantSkip: true},
		{name: "yes_skips", set: true, value: "yes", wantSkip: true},
		{name: "empty_skips", set: true, value: "", wantSkip: true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if tc.set {
				t.Setenv(segmentdistMeasureEnv, tc.value)
			} else {
				// t.Setenv restores on cleanup, so clearing it this way is scoped to
				// this subtest even when the ambient environment has it set — which it
				// does under `make measure-segmentdist`.
				t.Setenv(segmentdistMeasureEnv, "")
				if err := os.Unsetenv(segmentdistMeasureEnv); err != nil {
					t.Fatalf("unset %s: %v", segmentdistMeasureEnv, err)
				}
			}
			var inner *testing.T
			t.Run("probe", func(st *testing.T) {
				inner = st
				requireMeasurementRun(st)
			})
			if got := inner.Skipped(); got != tc.wantSkip {
				t.Errorf("%s=%q (set=%v): skipped=%v, want %v",
					segmentdistMeasureEnv, tc.value, tc.set, got, tc.wantSkip)
			}
		})
	}

	// The message names the variable, the exact value it needs, and the target — the
	// three things a reader of a skipped run has to learn from the skip alone.
	msg := measurementSkipMessage()
	for _, want := range []string{segmentdistMeasureEnv, segmentdistMeasureEnv + "=1", segmentdistMeasureTarget} {
		if !strings.Contains(msg, want) {
			t.Errorf("skip message does not name %q:\n%s", want, msg)
		}
	}
}
