// SPDX-License-Identifier: Apache-2.0

package thought

import (
	"context"
	"strings"

	knowledgev1 "github.com/fulminate-io/knowledge-mcp/gen/knowledge/v1"
	"github.com/fulminate-io/knowledge-mcp/internal/kgtypes"
)

// genre.go classifies a thought as MACHINE-genre (programmatically generated by
// the dream pipeline / a dream worker) versus HUMAN-genre (authored by an
// implementer/main/researcher agent). The blind-spots denominator uses this to
// EXCLUDE machine-genre clusters: a dream-generated code-smell cluster is thin on
// charges by construction (nobody charges machine observations), so counting it as
// an under-evidenced blind spot is noise, not signal.
//
// The classifier is DATA-DRIVEN over three node facets, each backed by a
// package-level marker set so the markers are data, not literals scattered through
// the switch. A thought is machine-genre if ANY facet matches.

// machineGenreSourcePrefixes are source-metadata prefixes marking a machine
// origin. "dream:" covers the legacy dream-pipeline corpus (e.g. source=
// "dream:analyze"). Source/origin prefixes are the PRIMARY signal.
var machineGenreSourcePrefixes = []string{"dream:"}

// machineGenreOriginPrefixes are origin-metadata prefixes marking a machine
// origin. "worker:" is the CURRENT dream-worker facet: a dream worker stamps
// origin="worker:<name>" on every thought it produces. The canonical const lives
// in the dream package (dream/eventbus.go workerOriginPrefix="worker:"), but the
// thought package cannot import dream (layering), so this is a DELIBERATE
// per-package mirror of the wire-stamped value — keep it in sync if the dream
// const changes. Source/origin prefixes are the PRIMARY signal.
var machineGenreOriginPrefixes = []string{"worker:"}

// machineGenreSessionMarkers are session-label substrings marking a machine
// session. "dream-code-smells" is the dream code-smell scan session. The session
// marker is a FALLBACK signal — used when neither the source nor origin facet
// carries a machine prefix but the enclosing session is a known machine session.
var machineGenreSessionMarkers = []string{"dream-code-smells"}

// isMachineGenreThought reports whether a thought is machine-genre, checking the
// three facets in priority order (source prefix, then origin prefix — the primary
// signals — then the enclosing-session marker fallback). enclosingSession is the
// thought's session label (empty when unknown / no session). Returns true if ANY
// facet matches.
func isMachineGenreThought(n *knowledgev1.Node, enclosingSession string) bool {
	if n == nil {
		return false
	}
	source := kgtypes.Value(n, "source")
	for _, p := range machineGenreSourcePrefixes {
		if strings.HasPrefix(source, p) {
			return true
		}
	}
	origin := kgtypes.Value(n, "origin")
	for _, p := range machineGenreOriginPrefixes {
		if strings.HasPrefix(origin, p) {
			return true
		}
	}
	for _, m := range machineGenreSessionMarkers {
		if m != "" && strings.Contains(enclosingSession, m) {
			return true
		}
	}
	return false
}

// FetchSessionLabelsByThought builds the thoughtID→enclosing-session-label map
// from ONE bulk EdgeKGContains read (NOT N per-thought lookups), reusing the
// deriveSessionSiblings group-by-session pattern: EdgeKGContains is
// session(From)→thought(To), so grouping the To endpoints by their From session
// node and hydrating the session nodes' SymbolName labels yields each thought's
// session label. Used by the blind-spots handler + loop to feed the session-marker
// facet of the genre classifier. A thought with no enclosing session is absent
// from the map (its lookup returns ""). Best-effort: a read error yields an empty
// map (the session-marker facet then never fires, leaving source/origin intact).
func FetchSessionLabelsByThought(ctx context.Context, gc Caller, thoughtIDs []string) map[string]string {
	out := map[string]string{}
	if gc == nil || len(thoughtIDs) == 0 {
		return out
	}
	idSet := make(map[string]bool, len(thoughtIDs))
	for _, id := range thoughtIDs {
		idSet[id] = true
	}
	edges, err := fetchEdgesForNodeSet(ctx, gc, thoughtIDs, []kgtypes.EdgeType{kgtypes.EdgeKGContains})
	if err != nil {
		return out
	}
	// Group thought members by their enclosing session (the From endpoint) and
	// collect the distinct session IDs to hydrate for their labels.
	thoughtsBySession := make(map[string][]string)
	sessionIDSet := map[string]bool{}
	for i := range edges {
		e := &edges[i]
		if kgtypes.EdgeType(e.Type) != kgtypes.EdgeKGContains {
			continue
		}
		if !idSet[e.ToId] { // pollution guard: only in-scope thought members.
			continue
		}
		thoughtsBySession[e.FromId] = append(thoughtsBySession[e.FromId], e.ToId)
		sessionIDSet[e.FromId] = true
	}
	if len(sessionIDSet) == 0 {
		return out
	}
	sessionIDs := make([]string, 0, len(sessionIDSet))
	for sid := range sessionIDSet {
		sessionIDs = append(sessionIDs, sid)
	}
	sessionNodes := fetchNodesByIDs(ctx, gc, sessionIDs)
	for sid, members := range thoughtsBySession {
		label := sid
		if n, ok := sessionNodes[sid]; ok && n.SymbolName != "" {
			label = n.SymbolName
		}
		for _, tid := range members {
			out[tid] = label
		}
	}
	return out
}

// clusterIsMachineGenre reports whether a cluster is machine-genre: true when a
// MAJORITY of its members classify as machine-genre. members are thought IDs;
// nodeByID hydrates the member nodes; sessionByThought maps a thought ID to its
// enclosing session label (built once via a bulk EdgeKGContains read). An empty
// member set is not machine-genre.
func clusterIsMachineGenre(members []string, nodeByID map[string]*knowledgev1.Node, sessionByThought map[string]string) bool {
	if len(members) == 0 {
		return false
	}
	machine := 0
	for _, id := range members {
		if isMachineGenreThought(nodeByID[id], sessionByThought[id]) {
			machine++
		}
	}
	return machine*2 > len(members)
}
