// SPDX-License-Identifier: Apache-2.0

package transcripts

import (
	"os"
	"path/filepath"
	"testing"
	"time"
)

// goldenTS is a terse RFC3339 UTC constructor for the golden fixture timestamps.
func goldenTS(s string) time.Time {
	t, err := time.Parse(time.RFC3339, s)
	if err != nil {
		panic(err)
	}
	return t
}

// clientGoldenRows is the DETERMINISTIC, hand-authored row set the client golden
// parquet is generated from. It is the cross-repo parity fixture: the agent's
// TestClientGoldenParquetQueryParity reads the generated bytes through the REAL
// DuckDB query builders, so this set is designed to exercise both the
// existing-logic aggregates and the enrichment queries.
//
// Row inventory (9 rows, all source=claude, record_type=assistant):
//
//	#  session  kind   model            tool  hash      day       tokens(in/out)  cache(rd/cr/1h/5m)  dur_ms  flags
//	1  sess-A   token  claude-fable-5   -     -         06-15     1000/200        50/100/40/60        1500    -
//	2  sess-A   tool   claude-fable-5   Bash  hashDUP   06-15     -               -                    300    -            <- dup pair (A)
//	3  sess-A   tool   claude-fable-5   Bash  hashDUP   06-15     -               -                    320    -            <- dup pair (A)
//	4  sess-A   tool   claude-fable-5   Grep  hashGREP  06-15     -               -                    100    is_error
//	5  sess-A   token  claude-fable-5   -     -         06-15     500/100         0/0/0/0              800    -
//	6  sess-B   token  claude-opus-4-8  -     -         06-16     2000/400        0/0/0/0             1200    -
//	7  sess-B   tool   claude-opus-4-8  Bash  hashDUP   06-16     -               -                    200    -            <- NEGATIVE control
//	8  sess-A   token  claude-fable-5   -     -         06-15      300/50         0/0/0/0              900    sidechain/researcher/agent-xyz
//	9  sess-A   tool   claude-fable-5   Read  hashREAD  06-15     -               -                    150    sidechain/researcher/agent-xyz
//
// DUPLICATE-COMMAND CONTROLS (GROUP BY session_id, tool_name, tool_input_hash HAVING COUNT>1):
//   - POSITIVE: (sess-A, Bash, hashDUP) = rows #2 + #3, count 2 → the ONE redundant
//     group the session-scoped query must return; wasted duration = SUM over the whole
//     group INCLUDING the first run = 300 + 320 = 620 ms.
//   - NEGATIVE control: (sess-B, Bash, hashDUP) = row #7 alone, count 1 → excluded. The
//     same tool_name+hash also lives under sess-A, so DROPPING session_id from the GROUP
//     BY would fold #2+#3+#7 into one count-3 group and surface this cross-session command
//     — the Phase 4 assertion fails in that case, which is the point of the control.
//
// SUBAGENT (is_sidechain, agent_id, subagent_type): rows #8 + #9 (agent-xyz / researcher).
//   - main-vs-subagent split: 7 main rows (#1-#7), 2 subagent rows (#8-#9).
//   - subagent wall-time = MAX(record_ts) − MIN(record_ts) GROUP BY agent_id:
//     agent-xyz = 10:31:30 − 10:30:00 = 90000 ms.
//
// KNOWN AGGREGATE TOTALS (all rows unless noted):
//   - total records: 9; distinct sessions: 2 (sess-A, sess-B); error rows: 1 (#4).
//   - total input_tokens: 3800 (1000+500+2000+300); output_tokens: 750 (200+100+400+50).
//   - cache_read_tokens: 50; cache_creation_tokens: 100; cache_1h: 40; cache_5m: 60.
//   - timeseries daily buckets: 2026-06-15 = 7 records (#1-#5,#8,#9); 2026-06-16 = 2 records (#6,#7).
//   - by model (records / input / output), ordered by total tokens desc:
//     claude-opus-4-8 = 2 rows (#6,#7)       / input 2000               / output 400  (total 2400)
//     claude-fable-5  = 7 rows (#1-#5,#8,#9) / input 1800 (1000+500+300) / output 350 (total 2150)
//   - total duration_ms: 5470 (1500+300+320+100+800+1200+200+900+150);
//     by model: claude-fable-5 = 4070 (#1-#5,#8,#9), claude-opus-4-8 = 1400 (#6,#7).
//   - session-scoped duplicate: (sess-A, Bash, hashDUP) run 2×, wasted 620 (300+320).
//   - subagent agent-xyz wall_ms 90000, tokens in 300 / out 50.
//   - avg tokens/session: in 1900, out 375, total 2275 over 2 sessions
//     (sess-A in 1800/out 350, sess-B in 2000/out 400).
func clientGoldenRows() []Row {
	const (
		fable = "claude-fable-5"
		opus  = "claude-opus-4-8"
	)
	mk := func(session, model, tool, hash, preview string, ts time.Time, dur int64) Row {
		return Row{
			Source: SourceClaude, SessionID: session, Project: "/Users/me/code/knowledge",
			GitBranch: "main", RecordTS: ts, RecordType: "assistant", Model: model,
			ToolName: tool, ToolInputHash: hash, ToolInputPreview: preview, DurationMs: dur,
		}
	}
	token := func(session, model string, in, out, cr, cc, c1h, c5m int64, ts time.Time, dur int64) Row {
		r := mk(session, model, "", "", "", ts, dur)
		r.InputTokens, r.OutputTokens = in, out
		r.CacheReadTokens, r.CacheCreationTokens = cr, cc
		r.CacheCreation1hTokens, r.CacheCreation5mTokens = c1h, c5m
		r.ServiceTier = "standard"
		return r
	}

	// #8/#9 subagent stamp.
	sub := func(r Row) Row {
		r.IsSidechain, r.AgentID, r.SubagentType = true, "agent-xyz", "researcher"
		return r
	}

	rows := []Row{
		token("sess-A", fable, 1000, 200, 50, 100, 40, 60, goldenTS("2026-06-15T10:00:00Z"), 1500), // #1
		mk("sess-A", fable, "Bash", "hashDUP", "ls -la", goldenTS("2026-06-15T10:00:01Z"), 300),    // #2
		mk("sess-A", fable, "Bash", "hashDUP", "ls -la", goldenTS("2026-06-15T10:00:02Z"), 320),    // #3
		func() Row { // #4 error tool row
			r := mk("sess-A", fable, "Grep", "hashGREP", "TODO", goldenTS("2026-06-15T10:00:03Z"), 100)
			r.IsError = true
			return r
		}(),
		token("sess-A", fable, 500, 100, 0, 0, 0, 0, goldenTS("2026-06-15T10:00:05Z"), 800),           // #5
		token("sess-B", opus, 2000, 400, 0, 0, 0, 0, goldenTS("2026-06-16T11:00:00Z"), 1200),          // #6
		mk("sess-B", opus, "Bash", "hashDUP", "ls -la", goldenTS("2026-06-16T11:00:01Z"), 200),        // #7 negative control
		sub(token("sess-A", fable, 300, 50, 0, 0, 0, 0, goldenTS("2026-06-15T10:30:00Z"), 900)),       // #8
		sub(mk("sess-A", fable, "Read", "hashREAD", "row.go", goldenTS("2026-06-15T10:31:30Z"), 150)), // #9
	}
	return rows
}

// TestGenerateClientGoldenParquet writes the deterministic client golden parquet
// to disk when WRITE_GOLDEN=1. It is the reproducible regenerator for the agent's
// cross-repo parity fixture (there was no regenerator before — the bytes were a
// committed binary). Normal `go test` runs skip it.
//
// Regenerate + install into the agent testdata:
//
//	WRITE_GOLDEN=1 GOLDEN_OUT=/abs/path/agent/cmd/agent/internal/domains/usageanalytics/testdata/client_golden.parquet \
//	  go test ./cmd/knowledge/internal/transcripts/ -run TestGenerateClientGoldenParquet -count=1
//
// If GOLDEN_OUT is unset it writes to $TMPDIR/client_golden.parquet and logs the
// path so the bytes can be copied into the agent testdata by hand.
func TestGenerateClientGoldenParquet(t *testing.T) {
	if os.Getenv("WRITE_GOLDEN") != "1" {
		t.Skip("set WRITE_GOLDEN=1 to (re)generate the client golden parquet")
	}
	out := os.Getenv("GOLDEN_OUT")
	if out == "" {
		out = filepath.Join(t.TempDir(), "client_golden.parquet")
	}
	f, err := os.Create(out) //nolint:gosec // out is an operator-supplied path for a dev-only regenerator.
	if err != nil {
		t.Fatalf("create %s: %v", out, err)
	}
	defer f.Close()

	if err := WriteSessionParquet(clientGoldenRows(), f); err != nil {
		t.Fatalf("WriteSessionParquet: %v", err)
	}
	t.Logf("wrote client golden parquet (%d rows) to %s", len(clientGoldenRows()), out)
}
